Summary.pdf: Summary.tex
	pdflatex -shell-escape Summary.tex
	pdflatex -shell-escape Summary.tex

all: Summary.pdf 

clean:
	rm -f Summary.aux  
	rm -f Summary.out  
	rm -f Summary.log 
	rm -f Summary.toc