arm-2d: /Users/gabwan01/Documents/Work/CPMK/Git/EndpointAI/Kernels/Research/Arm-2D/Library/Include/__arm_2d_impl.h File Reference
__arm_2d_impl.h File Reference
#include "arm_2d.h"
#include "__arm_2d_direct.h"
Data Structures
struct __arm_2d_point_adj_alpha_t
struct __arm_2d_low_level_io_t
struct __arm_2d_tile_param_t
struct __arm_2d_param_copy_t
struct __arm_2d_param_copy_msk_t
struct __arm_2d_param_copy_orig_t
struct __arm_2d_param_copy_orig_msk_t
struct __arm_2d_param_fill_t
struct __arm_2d_param_fill_msk_t
struct __arm_2d_param_fill_orig_t
struct __arm_2d_sub_task_t
struct __arm_2d_op_control
Macros
#define this (*ptThis)
#define OP_CORE this.use_as__arm_2d_op_core_t
#define ARM_2D_IMPL(__TYPE, ...)
#define ARM_2D_TRY_ACCELERATION(__ID, __FUNC_PROTOTYPE, ...)
#define ARM_2D_RUN_DEFAULT(__ID, __FUNC_PROTOTYPE, ...)
#define __ARM_2D_PIXEL_BLENDING_GRAY8(__SRC_ADDR, __DES_ADDR, __TRANS)
#define __ARM_2D_PIXEL_BLENDING_RGB565(__SRC_ADDR, __DES_ADDR, __TRANS)
#define __ARM_2D_PIXEL_BLENDING_CCCN888(__SRC_ADDR, __DES_ADDR, __TRANS)
#define __ARM_2D_PIXEL_BLENDING_OPA_GRAY8(__SRC_ADDR, __DES_ADDR, __OPA)
#define __ARM_2D_PIXEL_BLENDING_OPA_RGB565(__SRC_ADDR, __DES_ADDR, __OPA)
#define __ARM_2D_PIXEL_BLENDING_OPA_CCCN888(__SRC_ADDR, __DES_ADDR, __OPA)
#define __ARM_2D_PIXEL_AVERAGE_RGB565(__PIXEL_IN, __ALPHA)
#define __ARM_2D_PIXEL_AVERAGE_CCCN888(__PIXEL_IN, __ALPHA)
#define __ARM_2D_PIXEL_AVERAGE_GRAY8(__PIXEL_IN, __ALPHA)
Typedefs
typedef struct __arm_2d_point_adj_alpha_t __arm_2d_point_adj_alpha_t
typedef struct __arm_2d_sub_task_t __arm_2d_sub_task_t
typedef arm_fsm_rt_t __arm_2d_io_func_t(__arm_2d_sub_task_t *ptTask)
typedef struct __arm_2d_low_level_io_t __arm_2d_low_level_io_t
typedef struct __arm_2d_tile_param_t __arm_2d_tile_param_t
typedef struct __arm_2d_param_copy_t __arm_2d_param_copy_t
typedef struct __arm_2d_param_copy_msk_t __arm_2d_param_copy_msk_t
typedef struct __arm_2d_param_copy_orig_t __arm_2d_param_copy_orig_t
typedef struct __arm_2d_param_copy_orig_msk_t __arm_2d_param_copy_orig_msk_t
typedef struct __arm_2d_param_fill_t __arm_2d_param_fill_t
typedef struct __arm_2d_param_fill_msk_t __arm_2d_param_fill_msk_t
typedef struct __arm_2d_param_fill_orig_t __arm_2d_param_fill_orig_t
Enumerations
Operation Index: used for logging and debugging purpose
enum {
__ARM_2D_OP_IDX_BARRIER , __ARM_2D_OP_IDX_SYNC = __ARM_2D_OP_IDX_BARRIER , __ARM_2D_OP_IDX_COPY , __ARM_2D_OP_IDX_COPY_ONLY ,
__ARM_2D_OP_IDX_COPY_WITH_X_MIRROR , __ARM_2D_OP_IDX_COPY_WITH_Y_MIRROR , __ARM_2D_OP_IDX_COPY_WITH_XY_MIRROR , __ARM_2D_OP_IDX_FILL_ONLY ,
__ARM_2D_OP_IDX_FILL_WITH_X_MIRROR , __ARM_2D_OP_IDX_FILL_WITH_Y_MIRROR , __ARM_2D_OP_IDX_FILL_WITH_XY_MIRROR , __ARM_2D_OP_IDX_COPY_WITH_COLOUR_KEYING ,
__ARM_2D_OP_IDX_COPY_WITH_MASKS , __ARM_2D_OP_IDX_COPY_WITH_SOURCE_MASK , __ARM_2D_OP_IDX_COPY_WITH_TARGET_MASK , __ARM_2D_OP_IDX_FILL_COLOUR ,
__ARM_2D_OP_IDX_FILL_COLOUR_WITH_COLOUR_KEYING , __ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK , __ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK_AND_OPACITY , __ARM_2D_OP_IDX_ALPHA_BLENDING ,
__ARM_2D_OP_IDX_ALPHA_BLENDING_WITH_COLOUR_KEYING , __ARM_2D_OP_IDX_ALPHA_FILL_COLOUR , __ARM_2D_OP_IDX_ALPHA_FILL_COLOUR_WITH_COLOUR_KEYING , __ARM_2D_OP_IDX_DRAW_POINT ,
__ARM_2D_OP_IDX_DRAW_PATTERN , __ARM_2D_OP_IDX_COLOUR_FORMAT_CONVERSION , __ARM_2D_OP_IDX_TRANSFORM , __ARM_2D_OP_IDX_TRANSFORM_WITH_SOURCE_MASK ,
__ARM_2D_OP_IDX_TRANSFORM_WITH_OPACITY , __ARM_2D_OP_IDX_TRANSFORM_WITH_SOURCE_MASK_AND_OPACITY
}
Functions
arm_fsm_rt_t __arm_2d_op_invoke (arm_2d_op_core_t *ptOP)
bool __arm_2d_op_acquire (arm_2d_op_core_t *ptOP)
sync up with operation !
void __arm_2d_notify_sub_task_cpl (__arm_2d_sub_task_t *ptTask, arm_fsm_rt_t tResult, bool bFromHW)
arm_fsm_rt_t __arm_2d_op_frontend_op_decoder (arm_2d_op_core_t *ptThis)
arm_fsm_rt_t __arm_2d_op_depose (arm_2d_op_core_t *ptThis, arm_fsm_rt_t tResult)
__arm_2d_point_adj_alpha_t __arm_2d_point_get_adjacent_alpha_fp (arm_2d_point_float_t *ptPoint)
__arm_2d_point_adj_alpha_t __arm_2d_point_get_adjacent_alpha_q16 (arm_2d_point_fx_t *ptPoint)
arm_2d_err_t __arm_mask_validate (const arm_2d_tile_t *ptSource, const arm_2d_tile_t *ptSrcMask, const arm_2d_tile_t *ptTarget, const arm_2d_tile_t *ptDesMask, uint32_t wMode)
arm_fsm_rt_t __arm_2d_sw_draw_point (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_draw_pattern (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_draw_pattern (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_draw_pattern (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy_only (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy_only (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy_only (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy_x_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy_x_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy_x_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy_y_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy_y_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy_y_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy_xy_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy_xy_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy_xy_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill_only (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill_only (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill_only (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill_x_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill_x_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill_x_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill_y_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill_y_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill_y_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill_xy_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill_xy_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill_xy_mirror (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_tile_copy_with_masks (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_tile_fill_with_masks (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_copy_with_masks (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_fill_with_masks (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_copy_with_masks (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_fill_with_masks (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_tile_copy_with_src_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_tile_fill_with_src_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_copy_with_src_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_fill_with_src_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_copy_with_src_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_fill_with_src_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_tile_copy_with_des_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_tile_fill_with_des_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_copy_with_des_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_fill_with_des_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_copy_with_des_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_fill_with_des_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_c8bit_sw_colour_filling (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb16_sw_colour_filling (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb32_sw_colour_filling (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_alpha_blending (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_alpha_blending (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_alpha_blending (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_sw_convert_colour_to_rgb565 (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_sw_convert_colour_to_rgb888 (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_transform (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_transform (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_transform (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_transform_with_alpha (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_transform_with_alpha (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_transform_with_alpha (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_transform_with_src_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_transform_with_src_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_transform_with_src_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_transform_with_src_mask_and_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_transform_with_src_mask_and_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_transform_with_src_mask_and_opacity (__arm_2d_sub_task_t *ptTask)
Variables
const struct __arm_2d_io_table __ARM_2D_IO_TABLE
struct __arm_2d_op_control ARM_2D_CTRL
Macro Definition Documentation
__ARM_2D_PIXEL_AVERAGE_CCCN888
#define __ARM_2D_PIXEL_AVERAGE_CCCN888 (__PIXEL_IN, __ALPHA)
Value:
    do {                                                                        \
        arm_2d_color_rgb888_t tTempColour = {.tValue = (__PIXEL_IN)};           \
        tPixel.R += tTempColour.u8R * (__ALPHA);                                \
        tPixel.G += tTempColour.u8G * (__ALPHA);                                \
        tPixel.B += tTempColour.u8B * (__ALPHA);                                \
    } while(0)
Definition at line 197 of file __arm_2d_impl.h.
__ARM_2D_PIXEL_AVERAGE_GRAY8
#define __ARM_2D_PIXEL_AVERAGE_GRAY8 (__PIXEL_IN, __ALPHA)
Value:
    do {                                                                        \
        tPixel += (uint16_t)(__PIXEL_IN) * (uint16_t)(__ALPHA);                 \
    } while(0)
Definition at line 205 of file __arm_2d_impl.h.
__ARM_2D_PIXEL_AVERAGE_RGB565
#define __ARM_2D_PIXEL_AVERAGE_RGB565 (__PIXEL_IN, __ALPHA)
Value:
    do {                                                                        \
        __arm_2d_color_fast_rgb_t tTempColour;                                  \
        __arm_2d_rgb565_unpack((__PIXEL_IN), &tTempColour);                     \
        tPixel.R += tTempColour.R * (__ALPHA);                                  \
        tPixel.G += tTempColour.G * (__ALPHA);                                  \
        tPixel.B += tTempColour.B * (__ALPHA);                                  \
    } while(0)
Definition at line 187 of file __arm_2d_impl.h.
__ARM_2D_PIXEL_BLENDING_CCCN888
#define __ARM_2D_PIXEL_BLENDING_CCCN888 (__SRC_ADDR, __DES_ADDR, __TRANS)
Value:
            do {                                                                \
                uint16_t hwOPA = 256 - (__TRANS);                               \
                /* do not change alpha */                                       \
                uint_fast8_t ARM_2D_SAFE_NAME(n) = sizeof(uint32_t) - 1;        \
                const uint8_t *pchSrc = (uint8_t *)(__SRC_ADDR);                \
                uint8_t *pchDes = (uint8_t *)(__DES_ADDR);                      \
                                                                                \
                do {                                                            \
                    *pchDes = ( ((uint_fast16_t)(*pchSrc++) * hwOPA)            \
                              + ((uint_fast16_t)(*pchDes) * (__TRANS))          \
                              ) >> 8;                                           \
                     pchDes++;                                                  \
                } while(--ARM_2D_SAFE_NAME(n));                                 \
            } while(0)
Definition at line 123 of file __arm_2d_impl.h.
__ARM_2D_PIXEL_BLENDING_GRAY8
#define __ARM_2D_PIXEL_BLENDING_GRAY8 (__SRC_ADDR, __DES_ADDR, __TRANS)
Value:
            do {                                                                \
                uint16_t hwOPA = 256 - (__TRANS);                               \
                const uint8_t *pchSrc = (uint8_t *)(__SRC_ADDR);                \
                uint8_t *pchDes = (uint8_t *)(__DES_ADDR);                      \
                                                                                \
                *pchDes = ((uint16_t)( ((uint16_t)(*pchSrc++) * hwOPA)          \
                                     + ((uint16_t)(*pchDes) * (__TRANS))        \
                                     ) >> 8);                                   \
            } while(0)
Definition at line 93 of file __arm_2d_impl.h.
__ARM_2D_PIXEL_BLENDING_OPA_CCCN888
#define __ARM_2D_PIXEL_BLENDING_OPA_CCCN888 (__SRC_ADDR, __DES_ADDR, __OPA)
Value:
            do {                                                                \
                uint16_t hwTrans = 256 - (__OPA);                               \
                /* do not change alpha */                                       \
                uint_fast8_t ARM_2D_SAFE_NAME(n) = sizeof(uint32_t) - 1;        \
                const uint8_t *pchSrc = (uint8_t *)(__SRC_ADDR);                \
                uint8_t *pchDes = (uint8_t *)(__DES_ADDR);                      \
                                                                                \
                do {                                                            \
                    *pchDes = ( ((uint_fast16_t)(*pchSrc++) * (__OPA))          \
                              + ((uint_fast16_t)(*pchDes) * hwTrans)            \
                              ) >> 8;                                           \
                     pchDes++;                                                  \
                } while(--ARM_2D_SAFE_NAME(n));                                 \
            } while(0)
Definition at line 171 of file __arm_2d_impl.h.
__ARM_2D_PIXEL_BLENDING_OPA_GRAY8
#define __ARM_2D_PIXEL_BLENDING_OPA_GRAY8 (__SRC_ADDR, __DES_ADDR, __OPA)
Value:
            do {                                                                \
                uint16_t hwTrans = 256 - (__OPA);                               \
                const uint8_t *pchSrc = (uint8_t *)(__SRC_ADDR);                \
                uint8_t *pchDes = (uint8_t *)(__DES_ADDR);                      \
                                                                                \
                *pchDes = ((uint16_t)( ((uint16_t)(*pchSrc++) * (__OPA))        \
                                     + ((uint16_t)(*pchDes) * hwTrans)          \
                                     ) >> 8);                                   \
            } while(0)
Definition at line 141 of file __arm_2d_impl.h.
__ARM_2D_PIXEL_BLENDING_OPA_RGB565
#define __ARM_2D_PIXEL_BLENDING_OPA_RGB565 (__SRC_ADDR, __DES_ADDR, __OPA)
Value:
            do {                                                                \
                uint16_t hwTrans = 256 - (__OPA);                               \
                __arm_2d_color_fast_rgb_t tSrcPix, tTargetPix;                  \
                uint16_t *phwTargetPixel = (__DES_ADDR);                        \
                __arm_2d_rgb565_unpack(*(__SRC_ADDR), &tSrcPix);                \
                __arm_2d_rgb565_unpack(*phwTargetPixel, &tTargetPix);           \
                                                                                \
                for (int i = 0; i < 3; i++) {                                   \
                    uint16_t        hwTemp =                                    \
                        (uint16_t) (tSrcPix.RGBA[i] * (__OPA)) +                \
                        (tTargetPix.RGBA[i] * hwTrans);                         \
                    tTargetPix.RGBA[i] = (uint16_t) (hwTemp >> 8);              \
                }                                                               \
                                                                                \
                /* pack merged stream */                                        \
                *phwTargetPixel = __arm_2d_rgb565_pack(&tTargetPix);            \
            } while(0)
Definition at line 152 of file __arm_2d_impl.h.
__ARM_2D_PIXEL_BLENDING_RGB565
#define __ARM_2D_PIXEL_BLENDING_RGB565 (__SRC_ADDR, __DES_ADDR, __TRANS)
Value:
            do {                                                                \
                uint16_t hwOPA = 256 - (__TRANS);                               \
                __arm_2d_color_fast_rgb_t tSrcPix, tTargetPix;                  \
                uint16_t *phwTargetPixel = (__DES_ADDR);                        \
                __arm_2d_rgb565_unpack(*(__SRC_ADDR), &tSrcPix);                \
                __arm_2d_rgb565_unpack(*phwTargetPixel, &tTargetPix);           \
                                                                                \
                for (int i = 0; i < 3; i++) {                                   \
                    uint16_t        hwTemp =                                    \
                        (uint16_t) (tSrcPix.RGBA[i] * hwOPA) +                  \
                        (tTargetPix.RGBA[i] * (__TRANS));                       \
                    tTargetPix.RGBA[i] = (uint16_t) (hwTemp >> 8);              \
                }                                                               \
                                                                                \
                /* pack merged stream */                                        \
                *phwTargetPixel = __arm_2d_rgb565_pack(&tTargetPix);            \
            } while(0)
Definition at line 104 of file __arm_2d_impl.h.
ARM_2D_IMPL
#define ARM_2D_IMPL (__TYPE, ...)
Value:
            __TYPE *ptThis = (__TYPE *)(NULL,##__VA_ARGS__);                    \
            if (NULL == ptThis) {                                               \
                ptThis = (__TYPE *)&ARM_2D_CTRL.DefaultOP;                      \
            }
Definition at line 65 of file __arm_2d_impl.h.
ARM_2D_RUN_DEFAULT
#define ARM_2D_RUN_DEFAULT (__ID, __FUNC_PROTOTYPE, ...)
Value:
        if (    (NULL != OP_CORE.ptOp->Info.LowLevelIO.IO[__ID]->SW)            \
            &&  (NULL != OP_CORE.ptOp->Info.LowLevelIO.IO[__ID])) {             \
            tResult =                                                           \
            (*(__FUNC_PROTOTYPE *)OP_CORE.ptOp->Info.LowLevelIO.IO[__ID]->SW)(  \
                                        ptTask,                                 \
                                        ##__VA_ARGS__);                         \
        } else {                                                                \
            tResult = (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;                     \
        }
Definition at line 82 of file __arm_2d_impl.h.
ARM_2D_TRY_ACCELERATION
#define ARM_2D_TRY_ACCELERATION (__ID, __FUNC_PROTOTYPE, ...)
Value:
        if (    (NULL != OP_CORE.ptOp->Info.LowLevelIO.IO[__ID]->HW)            \
            &&  (NULL != OP_CORE.ptOp->Info.LowLevelIO.IO[__ID])) {             \
            tResult =                                                           \
            (*(__FUNC_PROTOTYPE *)OP_CORE.ptOp->Info.LowLevelIO.IO[__ID]->HW)(  \
                                        ptTask,                                 \
                                        ##__VA_ARGS__);                         \
        }
Definition at line 73 of file __arm_2d_impl.h.
OP_CORE
#define OP_CORE this.use_as__arm_2d_op_core_t
Definition at line 63 of file __arm_2d_impl.h.
this
#define this (*ptThis)
Definition at line 60 of file __arm_2d_impl.h.
Typedef Documentation
__arm_2d_io_func_t
typedef arm_fsm_rt_t __arm_2d_io_func_t(__arm_2d_sub_task_t *ptTask)
Definition at line 276 of file __arm_2d_impl.h.
__arm_2d_low_level_io_t
typedef struct __arm_2d_low_level_io_t __arm_2d_low_level_io_t
__arm_2d_param_copy_msk_t
typedef struct __arm_2d_param_copy_msk_t __arm_2d_param_copy_msk_t
__arm_2d_param_copy_orig_msk_t
typedef struct __arm_2d_param_copy_orig_msk_t __arm_2d_param_copy_orig_msk_t
__arm_2d_param_copy_orig_t
typedef struct __arm_2d_param_copy_orig_t __arm_2d_param_copy_orig_t
__arm_2d_param_copy_t
typedef struct __arm_2d_param_copy_t __arm_2d_param_copy_t
__arm_2d_param_fill_msk_t
typedef struct __arm_2d_param_fill_msk_t __arm_2d_param_fill_msk_t
__arm_2d_param_fill_orig_t
typedef struct __arm_2d_param_fill_orig_t __arm_2d_param_fill_orig_t
__arm_2d_param_fill_t
typedef struct __arm_2d_param_fill_t __arm_2d_param_fill_t
__arm_2d_point_adj_alpha_t
typedef struct __arm_2d_point_adj_alpha_t __arm_2d_point_adj_alpha_t
__arm_2d_sub_task_t
typedef struct __arm_2d_sub_task_t __arm_2d_sub_task_t
Definition at line 273 of file __arm_2d_impl.h.
__arm_2d_tile_param_t
typedef struct __arm_2d_tile_param_t __arm_2d_tile_param_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
__ARM_2D_OP_IDX_BARRIER
__ARM_2D_OP_IDX_SYNC
__ARM_2D_OP_IDX_COPY
__ARM_2D_OP_IDX_COPY_ONLY
__ARM_2D_OP_IDX_COPY_WITH_X_MIRROR
__ARM_2D_OP_IDX_COPY_WITH_Y_MIRROR
__ARM_2D_OP_IDX_COPY_WITH_XY_MIRROR
__ARM_2D_OP_IDX_FILL_ONLY
__ARM_2D_OP_IDX_FILL_WITH_X_MIRROR
__ARM_2D_OP_IDX_FILL_WITH_Y_MIRROR
__ARM_2D_OP_IDX_FILL_WITH_XY_MIRROR
__ARM_2D_OP_IDX_COPY_WITH_COLOUR_KEYING
__ARM_2D_OP_IDX_COPY_WITH_MASKS
__ARM_2D_OP_IDX_COPY_WITH_SOURCE_MASK
__ARM_2D_OP_IDX_COPY_WITH_TARGET_MASK
__ARM_2D_OP_IDX_FILL_COLOUR
__ARM_2D_OP_IDX_FILL_COLOUR_WITH_COLOUR_KEYING
__ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK
__ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK_AND_OPACITY
__ARM_2D_OP_IDX_ALPHA_BLENDING
__ARM_2D_OP_IDX_ALPHA_BLENDING_WITH_COLOUR_KEYING
__ARM_2D_OP_IDX_ALPHA_FILL_COLOUR
__ARM_2D_OP_IDX_ALPHA_FILL_COLOUR_WITH_COLOUR_KEYING
__ARM_2D_OP_IDX_DRAW_POINT
__ARM_2D_OP_IDX_DRAW_PATTERN
__ARM_2D_OP_IDX_COLOUR_FORMAT_CONVERSION
__ARM_2D_OP_IDX_TRANSFORM
__ARM_2D_OP_IDX_TRANSFORM_WITH_SOURCE_MASK
__ARM_2D_OP_IDX_TRANSFORM_WITH_OPACITY
__ARM_2D_OP_IDX_TRANSFORM_WITH_SOURCE_MASK_AND_OPACITY
Definition at line 224 of file __arm_2d_impl.h.
     {
    /*------------ arm-2d operation idx begin --------------*/
    __ARM_2D_OP_IDX_BARRIER,
    __ARM_2D_OP_IDX_SYNC = __ARM_2D_OP_IDX_BARRIER,
    __ARM_2D_OP_IDX_COPY,
    __ARM_2D_OP_IDX_COPY_ONLY,
    __ARM_2D_OP_IDX_COPY_WITH_X_MIRROR,
    __ARM_2D_OP_IDX_COPY_WITH_Y_MIRROR,
    __ARM_2D_OP_IDX_COPY_WITH_XY_MIRROR,
    __ARM_2D_OP_IDX_FILL_ONLY,
    __ARM_2D_OP_IDX_FILL_WITH_X_MIRROR,
    __ARM_2D_OP_IDX_FILL_WITH_Y_MIRROR,
    __ARM_2D_OP_IDX_FILL_WITH_XY_MIRROR,
    __ARM_2D_OP_IDX_COPY_WITH_COLOUR_KEYING,
    __ARM_2D_OP_IDX_COPY_WITH_MASKS,
    __ARM_2D_OP_IDX_COPY_WITH_SOURCE_MASK,
    __ARM_2D_OP_IDX_COPY_WITH_TARGET_MASK,
    __ARM_2D_OP_IDX_FILL_COLOUR,
    __ARM_2D_OP_IDX_FILL_COLOUR_WITH_COLOUR_KEYING,
    __ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK,
    __ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK_AND_OPACITY,
    __ARM_2D_OP_IDX_ALPHA_BLENDING,
    __ARM_2D_OP_IDX_ALPHA_BLENDING_WITH_COLOUR_KEYING,
    __ARM_2D_OP_IDX_ALPHA_FILL_COLOUR,
    __ARM_2D_OP_IDX_ALPHA_FILL_COLOUR_WITH_COLOUR_KEYING,
    __ARM_2D_OP_IDX_DRAW_POINT,
    __ARM_2D_OP_IDX_DRAW_PATTERN,
    __ARM_2D_OP_IDX_COLOUR_FORMAT_CONVERSION,
    __ARM_2D_OP_IDX_TRANSFORM,
    //__ARM_2D_OP_IDX_TRANSFORM_WITH_MASKS,                                     //!< todo in v1.xx
    __ARM_2D_OP_IDX_TRANSFORM_WITH_SOURCE_MASK,
    //__ARM_2D_OP_IDX_TRANSFORM_WITH_TARGET_MASK,                               //!< todo in v1.xx
    __ARM_2D_OP_IDX_TRANSFORM_WITH_OPACITY,
    //__ARM_2D_OP_IDX_TRANSFORM_WITH_MASKS_AND_OPACITY,                         //!< todo in v1.xx
    __ARM_2D_OP_IDX_TRANSFORM_WITH_SOURCE_MASK_AND_OPACITY,
    //__ARM_2D_OP_IDX_TRANSFORM_WITH_TARGET_MASK_AND_OPACITY,                   //!< todo in v1.xx
    /*------------ cmsisi-2d operation idx end --------------*/
};
Function Documentation
__arm_2d_c8bit_sw_colour_filling()
arm_fsm_rt_t __arm_2d_c8bit_sw_colour_filling (__arm_2d_sub_task_t * ptTask)
Definition at line 313 of file arm_2d_draw.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_SZ_8BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    __arm_2d_impl_c8bit_colour_filling(
                    ptTask->Param.tTileProcess.pBuffer,
                    ptTask->Param.tTileProcess.iStride,
                    &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                    this.chColour);
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_c8bit_sw_draw_pattern()
arm_fsm_rt_t __arm_2d_c8bit_sw_draw_pattern (__arm_2d_sub_task_t * ptTask)
draw bit-pattern
Definition at line 489 of file arm_2d_draw.c.
{
    ARM_2D_IMPL(arm_2d_op_drw_patn_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_SZ_8BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    uint32_t wMode = this.wMode;
#if 0
    if (!this.Source.ptTile->bHasEnforcedColour) {
        return (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;
    }
    if (ARM_2D_COLOUR_SZ_1BIT != this.Source.ptTile->tColourInfo.u3ColourSZ) {
        return (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;
    }
#endif
    if (wMode & (ARM_2D_CP_MODE_Y_MIRROR | ARM_2D_CP_MODE_X_MIRROR)) {
    #if 0
        __arm_2d_impl_c8bit_draw_pattern_with_mirror(
                                    ptTask->Param.tCopy.pSource ,
                                    ptTask->Param.tCopy.iSourceStride,
                                    ptTask->Param.tCopy.pTarget,
                                    ptTask->Param.tCopy.iTargetStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    wMode);
        break;
    #else
        return (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;
    #endif
    } else {
        __arm_2d_impl_c8bit_draw_pattern(
                                ptTask->Param.tCopy.tSource.pBuffer,
                                ptTask->Param.tCopy.tSource.nOffset,
                                ptTask->Param.tCopy.tSource.iStride,
                                ptTask->Param.tCopy.tTarget.pBuffer,
                                ptTask->Param.tCopy.tTarget.iStride,
                                &ptTask->Param.tCopy.tCopySize,
                                wMode,
                                this.Foreground.hwColour,
                                this.Background.hwColour);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_c8bit_sw_tile_copy()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_copy_only()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy_only (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_copy_with_colour_keying()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy_with_colour_keying (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_copy_x_mirror()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy_x_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_copy_xy_mirror()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy_xy_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_copy_y_mirror()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_copy_y_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_fill()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_fill_only()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill_only (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_fill_with_colour_keying()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill_with_colour_keying (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_fill_x_mirror()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill_x_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_fill_xy_mirror()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill_xy_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_c8bit_sw_tile_fill_y_mirror()
arm_fsm_rt_t __arm_2d_c8bit_sw_tile_fill_y_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_cccn888_sw_alpha_blending()
arm_fsm_rt_t __arm_2d_cccn888_sw_alpha_blending (__arm_2d_sub_task_t * ptTask)
Definition at line 752 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb32_copy(   ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize);
    } else {
        __arm_2d_impl_cccn888_alpha_blending(
                                            ptTask->Param.tCopy.tSource.pBuffer,
                                            ptTask->Param.tCopy.tSource.iStride,
                                            ptTask->Param.tCopy.tTarget.pBuffer,
                                            ptTask->Param.tCopy.tTarget.iStride,
                                            &(ptTask->Param.tCopy.tCopySize),
                                            this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_cccn888_sw_alpha_blending_with_colour_keying()
arm_fsm_rt_t __arm_2d_cccn888_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t * ptTask)
Definition at line 1603 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_cl_key_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb32_cl_key_copy(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.wColour);
    } else {
    __arm_2d_impl_cccn888_alpha_blending_colour_keying(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.chRatio,
                                    this.wColour);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_cccn888_sw_colour_filling_with_mask()
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_mask (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
Definition at line 1120 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_msk_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        __arm_2d_impl_cccn888_colour_filling_channel_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.hwColour);
    #endif
    } else {
        __arm_2d_impl_cccn888_colour_filling_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.hwColour);
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_cccn888_colour_filling_channel_mask(), __arm_2d_impl_cccn888_colour_filling_mask(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_cccn888_sw_colour_filling_with_mask_and_opacity()
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
< alpha tile
< alpha tile
Definition at line 1388 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_fill_cl_msk_opc_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        if (255 == this.chRatio) {
            __arm_2d_impl_cccn888_colour_filling_channel_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour);
        } else {
            __arm_2d_impl_cccn888_colour_filling_channel_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour,
                            this.chRatio);
        }
    #endif
    } else {
        if (255 == this.chRatio) {
            __arm_2d_impl_cccn888_colour_filling_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour);
        } else {
            __arm_2d_impl_cccn888_colour_filling_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour,
                            this.chRatio);
        }
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_cccn888_colour_filling_channel_mask(), __arm_2d_impl_cccn888_colour_filling_channel_mask_opacity(), __arm_2d_impl_cccn888_colour_filling_mask(), __arm_2d_impl_cccn888_colour_filling_mask_opacity(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_cccn888_sw_colour_filling_with_opacity()
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_opacity (__arm_2d_sub_task_t * ptTask)
Definition at line 911 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_opc_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb32_colour_filling(
                            ptTask->Param.tTileProcess.pBuffer,
                            ptTask->Param.tTileProcess.iStride,
                            &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                            this.wColour );
    } else {
        __arm_2d_impl_cccn888_colour_filling_with_opacity(
                        ptTask->Param.tTileProcess.pBuffer,
                        ptTask->Param.tTileProcess.iStride,
                        &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                        this.wColour,
                        this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_cccn888_sw_tile_copy_with_des_mask()
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_copy_with_des_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_cccn888_sw_tile_copy_with_masks()
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_copy_with_masks (__arm_2d_sub_task_t * ptTask)
__arm_2d_cccn888_sw_tile_copy_with_src_mask()
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_copy_with_src_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_cccn888_sw_tile_fill_with_des_mask()
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_fill_with_des_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_cccn888_sw_tile_fill_with_masks()
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_fill_with_masks (__arm_2d_sub_task_t * ptTask)
__arm_2d_cccn888_sw_tile_fill_with_src_mask()
arm_fsm_rt_t __arm_2d_cccn888_sw_tile_fill_with_src_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_cccn888_sw_transform()
arm_fsm_rt_t __arm_2d_cccn888_sw_transform (__arm_2d_sub_task_t * ptTask)
Definition at line 817 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    __arm_2d_impl_cccn888_transform(&(ptTask->Param.tCopyOrig),
                                    &this.tTransform);
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_cccn888_sw_transform_with_alpha()
arm_fsm_rt_t __arm_2d_cccn888_sw_transform_with_alpha (__arm_2d_sub_task_t * ptTask)
Definition at line 963 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_opa_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (255 == this.chOpacity) {
        __arm_2d_impl_cccn888_transform(&(ptTask->Param.tCopyOrig),
                                        &this.tTransform);
    } else {
        __arm_2d_impl_cccn888_transform_with_opacity(  &(ptTask->Param.tCopyOrig),
                                                &this.tTransform,
                                                this.chOpacity);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_cccn888_sw_transform_with_src_mask()
arm_fsm_rt_t __arm_2d_cccn888_sw_transform_with_src_mask (__arm_2d_sub_task_t * ptTask)
Definition at line 1208 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_msk_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
#if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
    bool bIsMaskChannel8In32 = (ARM_2D_CHANNEL_8in32
            ==  ptTask->Param.tCopyOrigMask.tOrigMask.tColour.chScheme);
    if (bIsMaskChannel8In32) {
        __arm_2d_impl_cccn888_transform_with_src_chn_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
    } else
#endif
    {
        __arm_2d_impl_cccn888_transform_with_src_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_cccn888_sw_transform_with_src_mask_and_opacity()
arm_fsm_rt_t __arm_2d_cccn888_sw_transform_with_src_mask_and_opacity (__arm_2d_sub_task_t * ptTask)
Definition at line 1453 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_msk_opa_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
#if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
    bool bIsMaskChannel8In32 = (ARM_2D_CHANNEL_8in32
            ==  ptTask->Param.tCopyOrigMask.tOrigMask.tColour.chScheme);
#endif
    if (255 == this.chOpacity) {
    #if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        if (bIsMaskChannel8In32) {
            __arm_2d_impl_cccn888_transform_with_src_chn_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
        } else
    #endif
        {
            __arm_2d_impl_cccn888_transform_with_src_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
        }
    } else {
    #if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        if (bIsMaskChannel8In32) {
            __arm_2d_impl_cccn888_transform_with_src_chn_mask_and_opacity(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform,
                                                this.chOpacity);
        } else
    #endif
        {
            __arm_2d_impl_cccn888_transform_with_src_mask_and_opacity(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform,
                                                this.chOpacity);
        }
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_gray8_sw_alpha_blending()
arm_fsm_rt_t __arm_2d_gray8_sw_alpha_blending (__arm_2d_sub_task_t * ptTask)
Definition at line 703 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_c8bit_copy(   ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize);
    } else {
        __arm_2d_impl_gray8_alpha_blending(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &(ptTask->Param.tCopy.tCopySize),
                                    this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_gray8_sw_alpha_blending_with_colour_keying()
arm_fsm_rt_t __arm_2d_gray8_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t * ptTask)
Definition at line 1547 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_cl_key_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_GRAY8 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_c8bit_cl_key_copy(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.chColour);
    } else {
        __arm_2d_impl_gray8_alpha_blending_colour_keying(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.chRatio,
                                    this.chColour);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_gray8_sw_colour_filling_with_mask()
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_mask (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
Definition at line 1058 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_msk_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_16BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        __arm_2d_impl_gray8_colour_filling_channel_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.chColour);
    #endif
    } else {
        __arm_2d_impl_gray8_colour_filling_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.chColour);
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_gray8_colour_filling_channel_mask(), __arm_2d_impl_gray8_colour_filling_mask(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_gray8_sw_colour_filling_with_mask_and_opacity()
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
< alpha tile
< alpha tile
Definition at line 1283 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_fill_cl_msk_opc_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_16BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        if (255 == this.chRatio) {
            __arm_2d_impl_gray8_colour_filling_channel_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.chColour);
        } else {
            __arm_2d_impl_gray8_colour_filling_channel_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.chColour,
                            this.chRatio);
        }
    #endif
    } else {
        if (255 == this.chRatio) {
            __arm_2d_impl_gray8_colour_filling_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.chColour);
        } else {
            __arm_2d_impl_gray8_colour_filling_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.chColour,
                            this.chRatio);
        }
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_gray8_colour_filling_channel_mask(), __arm_2d_impl_gray8_colour_filling_channel_mask_opacity(), __arm_2d_impl_gray8_colour_filling_mask(), __arm_2d_impl_gray8_colour_filling_mask_opacity(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_gray8_sw_colour_filling_with_opacity()
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_opacity (__arm_2d_sub_task_t * ptTask)
Definition at line 864 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_opc_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_GRAY8 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_c8bit_colour_filling(
                            ptTask->Param.tTileProcess.pBuffer,
                            ptTask->Param.tTileProcess.iStride,
                            &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                            this.chColour );
    } else {
        __arm_2d_impl_gray8_colour_filling_with_opacity(
                                ptTask->Param.tTileProcess.pBuffer,
                                ptTask->Param.tTileProcess.iStride,
                                &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                                this.chColour,
                                this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_gray8_sw_tile_copy_with_des_mask()
arm_fsm_rt_t __arm_2d_gray8_sw_tile_copy_with_des_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_gray8_sw_tile_copy_with_masks()
arm_fsm_rt_t __arm_2d_gray8_sw_tile_copy_with_masks (__arm_2d_sub_task_t * ptTask)
__arm_2d_gray8_sw_tile_copy_with_src_mask()
arm_fsm_rt_t __arm_2d_gray8_sw_tile_copy_with_src_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_gray8_sw_tile_fill_with_des_mask()
arm_fsm_rt_t __arm_2d_gray8_sw_tile_fill_with_des_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_gray8_sw_tile_fill_with_masks()
arm_fsm_rt_t __arm_2d_gray8_sw_tile_fill_with_masks (__arm_2d_sub_task_t * ptTask)
__arm_2d_gray8_sw_tile_fill_with_src_mask()
arm_fsm_rt_t __arm_2d_gray8_sw_tile_fill_with_src_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_gray8_sw_transform()
arm_fsm_rt_t __arm_2d_gray8_sw_transform (__arm_2d_sub_task_t * ptTask)
Definition at line 794 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_8BIT == OP_CORE.ptOp->Info.Colour.chScheme);
    __arm_2d_impl_gray8_transform(  &(ptTask->Param.tCopyOrig),
                                    &this.tTransform);
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_gray8_sw_transform_with_alpha()
arm_fsm_rt_t __arm_2d_gray8_sw_transform_with_alpha (__arm_2d_sub_task_t * ptTask)
Definition at line 929 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_opa_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_GRAY8 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chOpacity) {
        __arm_2d_impl_gray8_transform(  &(ptTask->Param.tCopyOrig),
                                        &this.tTransform);
    } else {
        __arm_2d_impl_gray8_transform_with_opacity(  &(ptTask->Param.tCopyOrig),
                                            &this.tTransform,
                                            this.chOpacity);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_gray8_sw_transform_with_src_mask()
arm_fsm_rt_t __arm_2d_gray8_sw_transform_with_src_mask (__arm_2d_sub_task_t * ptTask)
Definition at line 1158 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_msk_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_8BIT == OP_CORE.ptOp->Info.Colour.chScheme);
#if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
    bool bIsMaskChannel8In32 = (ARM_2D_CHANNEL_8in32
            ==  ptTask->Param.tCopyOrigMask.tOrigMask.tColour.chScheme);
    if (bIsMaskChannel8In32) {
        __arm_2d_impl_gray8_transform_with_src_chn_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
    } else
#endif
    {
        __arm_2d_impl_gray8_transform_with_src_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_gray8_sw_transform_with_src_mask_and_opacity()
arm_fsm_rt_t __arm_2d_gray8_sw_transform_with_src_mask_and_opacity (__arm_2d_sub_task_t * ptTask)
Definition at line 1364 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_msk_opa_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_8BIT == OP_CORE.ptOp->Info.Colour.chScheme);
#if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
    bool bIsMaskChannel8In32 = (ARM_2D_CHANNEL_8in32
            ==  ptTask->Param.tCopyOrigMask.tOrigMask.tColour.chScheme);
#endif
    if (255 == this.chOpacity) {
    #if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        if (bIsMaskChannel8In32) {
            __arm_2d_impl_gray8_transform_with_src_chn_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
        } else
    #endif
        {
            __arm_2d_impl_gray8_transform_with_src_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
        }
    } else {
    #if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        if (bIsMaskChannel8In32) {
            __arm_2d_impl_gray8_transform_with_src_chn_mask_and_opacity(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform,
                                                this.chOpacity);
        } else
    #endif
        {
            __arm_2d_impl_gray8_transform_with_src_mask_and_opacity(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform,
                                                this.chOpacity);
        }
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_notify_sub_task_cpl()
void __arm_2d_notify_sub_task_cpl (__arm_2d_sub_task_t * ptTask, arm_fsm_rt_t tResult, bool bFromHW)
Note
This API should be called by both arm_2d_task and hardware ! accelerator to indicate the completion of a sub task
__arm_2d_op_acquire()
bool __arm_2d_op_acquire (arm_2d_op_core_t * ptOP)
sync up with operation !
Return values
true operation is busy !
false operation isn't busy
__arm_2d_op_depose()
arm_fsm_rt_t __arm_2d_op_depose (arm_2d_op_core_t * ptThis, arm_fsm_rt_t tResult)
__arm_2d_op_frontend_op_decoder()
arm_fsm_rt_t __arm_2d_op_frontend_op_decoder (arm_2d_op_core_t * ptThis)
__arm_2d_op_invoke()
arm_fsm_rt_t __arm_2d_op_invoke (arm_2d_op_core_t * ptOP)
__arm_2d_point_get_adjacent_alpha_fp()
__arm_2d_point_adj_alpha_t __arm_2d_point_get_adjacent_alpha_fp (arm_2d_point_float_t * ptPoint)
< x
< y
< x
< y
< x
< y
Definition at line 147 of file arm_2d_transform.c.
{
    assert(NULL != ptPoint);
    float x = ptPoint->fX - (int32_t)ptPoint->fX;
    float y = ptPoint->fY - (int32_t)ptPoint->fY;
    int16_t iXSign = x < 0 ;
    int16_t iYSign = y < 0 ;
    __arm_2d_point_adj_alpha_t tResult = {
        .tMatrix = {
            [0] = {
                .tOffset = {
                    .iX = -iXSign,
                    .iY = -iYSign,
                },
            #if 0
                .chAlpha = (uint8_t)(
                                ((float)(1-iXSign)  - (float)x)
                            *   ((float)(1-iYSign)  - (float)y)
                            *   256.0f
                            ),
            #endif
            },
            [1] = {
                .tOffset = {
                    .iX = -iXSign + 1,
                    .iY = -iYSign,
                },
                .chAlpha = (uint8_t)(
                                ((float)iXSign      + (float)x)
                            *   ((float)(1-iYSign)  - (float)y)
                            *   256.0f
                            ),
            },
            [2] = {
                .tOffset = {
                    .iX = -iXSign,
                    .iY = -iYSign + 1,
                },
                .chAlpha = (uint8_t)(
                                ((float)(1-iXSign)  - (float)x)
                            *   ((float)iYSign      + (float)y)
                            *   256.0f
                            ),
            },
            [3] = {
                .tOffset = {
                    .iX = -iXSign + 1,
                    .iY = -iYSign +1,
                },
                .chAlpha = (uint8_t)(
                                ((float)iXSign      + (float)x)
                            *   ((float)iYSign      + (float)y)
                            *   256.0f
                            ),
            },
        },
    };
#if 1
    tResult.tMatrix[0].chAlpha  = 256
                                - tResult.tMatrix[1].chAlpha
                                - tResult.tMatrix[2].chAlpha
                                - tResult.tMatrix[3].chAlpha;
#endif
    return tResult;
}
__arm_2d_point_get_adjacent_alpha_q16()
__arm_2d_point_adj_alpha_t __arm_2d_point_get_adjacent_alpha_q16 (arm_2d_point_fx_t * ptPoint)
< x
< y
< x
< y
< x
< y
Definition at line 216 of file arm_2d_transform.c.
{
    assert(NULL != ptPoint);
    int32_t x = ptPoint->X  & 0xFFFF;
    int32_t y = ptPoint->Y  & 0xFFFF;
    x |= ((ptPoint->X < 0) * 0xFFFF0000);
    y |= ((ptPoint->Y < 0) * 0xFFFF0000);
    int_fast16_t iXSign = x < 0;// ? 1 : 0;
    int_fast16_t iYSign = y < 0;// ? 1 : 0;
    __arm_2d_point_adj_alpha_t tResult = {
        .tMatrix = {
            [0] = {
                .tOffset = {
                    .iX = -iXSign,
                    .iY = -iYSign,
                },
            #if 0
                .chAlpha = (uint8_t)__USAT(
             MUL_Q16(MUL_Q16(   (TO_Q16(1-iXSign)   - x)
                            ,   (TO_Q16(1-iYSign)   - y))
                            ,   TO_Q16(256)
                            ) >> 16, 8),
            #endif
            },
            [1] = {
                .tOffset = {
                    .iX = -iXSign + 1,
                    .iY = -iYSign,
                },
                .chAlpha = (uint8_t)__USAT(
             MUL_Q16(MUL_Q16(   (TO_Q16(iXSign)     + x)
                            ,   (TO_Q16(1-iYSign)   - y))
                            ,   TO_Q16(256)
                            ) >> 16, 8),
            },
            [2] = {
                .tOffset = {
                    .iX = -iXSign,
                    .iY = -iYSign + 1,
                },
                .chAlpha = (uint8_t)__USAT(
             MUL_Q16(MUL_Q16(   (TO_Q16(1-iXSign)   - x)
                            ,   (TO_Q16(iYSign)     + y))
                            ,   TO_Q16(256)
                            ) >> 16, 8),
            },
            [3] = {
                .tOffset = {
                    .iX = -iXSign + 1,
                    .iY = -iYSign +1,
                },
                .chAlpha = (uint8_t)__USAT(
             MUL_Q16(MUL_Q16(   (TO_Q16(iXSign)     + x)
                            ,   (TO_Q16(iYSign)     + y))
                            ,   TO_Q16(256)
                            ) >> 16, 8),
            },
        },
    };
#if 1
    tResult.tMatrix[0].chAlpha  = 256
                                - tResult.tMatrix[1].chAlpha
                                - tResult.tMatrix[2].chAlpha
                                - tResult.tMatrix[3].chAlpha;
#endif
    return tResult;
}
__arm_2d_rgb16_sw_colour_filling()
arm_fsm_rt_t __arm_2d_rgb16_sw_colour_filling (__arm_2d_sub_task_t * ptTask)
Definition at line 327 of file arm_2d_draw.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_SZ_16BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    __arm_2d_impl_rgb16_colour_filling(
                    ptTask->Param.tTileProcess.pBuffer,
                    ptTask->Param.tTileProcess.iStride,
                    &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                    this.hwColour);
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb16_sw_draw_pattern()
arm_fsm_rt_t __arm_2d_rgb16_sw_draw_pattern (__arm_2d_sub_task_t * ptTask)
draw bit-pattern
Definition at line 536 of file arm_2d_draw.c.
{
    ARM_2D_IMPL(arm_2d_op_drw_patn_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_SZ_16BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    uint32_t wMode = this.wMode;
#if 0
    if (!this.Source.ptTile->bHasEnforcedColour) {
        return (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;
    }
    if (ARM_2D_COLOUR_SZ_1BIT != this.Source.ptTile->tColourInfo.u3ColourSZ) {
        return (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;
    }
#endif
    if (wMode & (ARM_2D_CP_MODE_Y_MIRROR | ARM_2D_CP_MODE_X_MIRROR)) {
    #if 0
        __arm_2d_impl_rgb16_draw_pattern_with_mirror(
                                    ptTask->Param.tCopy.pSource ,
                                    ptTask->Param.tCopy.iSourceStride,
                                    ptTask->Param.tCopy.pTarget,
                                    ptTask->Param.tCopy.iTargetStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    wMode);
        break;
    #else
        return (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;
    #endif
    } else {
        __arm_2d_impl_rgb16_draw_pattern(
                                ptTask->Param.tCopy.tSource.pBuffer,
                                ptTask->Param.tCopy.tSource.nOffset,
                                ptTask->Param.tCopy.tSource.iStride,
                                ptTask->Param.tCopy.tTarget.pBuffer,
                                ptTask->Param.tCopy.tTarget.iStride,
                                &ptTask->Param.tCopy.tCopySize,
                                wMode,
                                this.Foreground.hwColour,
                                this.Background.hwColour);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb16_sw_tile_copy()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_copy_only()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy_only (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_copy_with_colour_keying()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy_with_colour_keying (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_copy_x_mirror()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy_x_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_copy_xy_mirror()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy_xy_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_copy_y_mirror()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_copy_y_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_fill()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_fill_only()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill_only (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_fill_with_colour_keying()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill_with_colour_keying (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_fill_x_mirror()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill_x_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_fill_xy_mirror()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill_xy_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb16_sw_tile_fill_y_mirror()
arm_fsm_rt_t __arm_2d_rgb16_sw_tile_fill_y_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_colour_filling()
arm_fsm_rt_t __arm_2d_rgb32_sw_colour_filling (__arm_2d_sub_task_t * ptTask)
Definition at line 341 of file arm_2d_draw.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    __arm_2d_impl_rgb32_colour_filling(
                    ptTask->Param.tTileProcess.pBuffer,
                    ptTask->Param.tTileProcess.iStride,
                    &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                    this.wColour);
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb32_sw_draw_pattern()
arm_fsm_rt_t __arm_2d_rgb32_sw_draw_pattern (__arm_2d_sub_task_t * ptTask)
Definition at line 583 of file arm_2d_draw.c.
{
    ARM_2D_IMPL(arm_2d_op_drw_patn_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    uint32_t wMode = this.wMode;
#if 0
    if (!this.Source.ptTile->bHasEnforcedColour) {
        return (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;
    }
    if (ARM_2D_COLOUR_SZ_1BIT != this.Source.ptTile->tColourInfo.u3ColourSZ) {
        return (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;
    }
#endif
    if (wMode & (ARM_2D_CP_MODE_Y_MIRROR | ARM_2D_CP_MODE_X_MIRROR)) {
    #if 0
        __arm_2d_impl_rgb32_draw_pattern_with_mirror(
                                    ptTask->Param.tCopy.pSource ,
                                    ptTask->Param.tCopy.iSourceStride,
                                    ptTask->Param.tCopy.pTarget,
                                    ptTask->Param.tCopy.iTargetStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    wMode);
    #else
        return (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;
    #endif
    } else {
        __arm_2d_impl_rgb32_draw_pattern(
                                ptTask->Param.tCopy.tSource.pBuffer,
                                ptTask->Param.tCopy.tSource.nOffset,
                                ptTask->Param.tCopy.tSource.iStride,
                                ptTask->Param.tCopy.tTarget.pBuffer,
                                ptTask->Param.tCopy.tTarget.iStride,
                                &ptTask->Param.tCopy.tCopySize,
                                wMode,
                                this.Foreground.wColour,
                                this.Background.wColour);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb32_sw_tile_copy()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_copy_only()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy_only (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_copy_with_colour_keying()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy_with_colour_keying (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_copy_x_mirror()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy_x_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_copy_xy_mirror()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy_xy_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_copy_y_mirror()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_copy_y_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_fill()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_fill_only()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill_only (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_fill_with_colour_keying()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill_with_colour_keying (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_fill_x_mirror()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill_x_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_fill_xy_mirror()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill_xy_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb32_sw_tile_fill_y_mirror()
arm_fsm_rt_t __arm_2d_rgb32_sw_tile_fill_y_mirror (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb565_sw_alpha_blending()
arm_fsm_rt_t __arm_2d_rgb565_sw_alpha_blending (__arm_2d_sub_task_t * ptTask)
Definition at line 727 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb16_copy(   ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize);
    } else {
        __arm_2d_impl_rgb565_alpha_blending(
                                ptTask->Param.tCopy.tSource.pBuffer,
                                ptTask->Param.tCopy.tSource.iStride,
                                ptTask->Param.tCopy.tTarget.pBuffer,
                                ptTask->Param.tCopy.tTarget.iStride,
                                &(ptTask->Param.tCopy.tCopySize),
                                this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb565_sw_alpha_blending_with_colour_keying()
arm_fsm_rt_t __arm_2d_rgb565_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t * ptTask)
Definition at line 1575 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_cl_key_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb16_cl_key_copy(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.hwColour);
    } else {
        __arm_2d_impl_rgb565_alpha_blending_colour_keying(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.chRatio,
                                    this.hwColour);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb565_sw_colour_filling_with_mask()
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_mask (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
Definition at line 1090 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_msk_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_16BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        __arm_2d_impl_rgb565_colour_filling_channel_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.hwColour);
    #endif
    } else {
        __arm_2d_impl_rgb565_colour_filling_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.hwColour);
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_rgb565_colour_filling_channel_mask(), __arm_2d_impl_rgb565_colour_filling_mask(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_rgb565_sw_colour_filling_with_mask_and_opacity()
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
< alpha tile
< alpha tile
Definition at line 1336 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_fill_cl_msk_opc_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_16BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        if (255 == this.chRatio) {
            __arm_2d_impl_rgb565_colour_filling_channel_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour);
        } else {
            __arm_2d_impl_rgb565_colour_filling_channel_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour,
                            this.chRatio);
        }
    #endif
    } else {
        if (255 == this.chRatio) {
            __arm_2d_impl_rgb565_colour_filling_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour);
        } else {
            __arm_2d_impl_rgb565_colour_filling_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour,
                            this.chRatio);
        }
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_rgb565_colour_filling_channel_mask(), __arm_2d_impl_rgb565_colour_filling_channel_mask_opacity(), __arm_2d_impl_rgb565_colour_filling_mask(), __arm_2d_impl_rgb565_colour_filling_mask_opacity(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_rgb565_sw_colour_filling_with_opacity()
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_opacity (__arm_2d_sub_task_t * ptTask)
Definition at line 887 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_opc_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb16_colour_filling(
                            ptTask->Param.tTileProcess.pBuffer,
                            ptTask->Param.tTileProcess.iStride,
                            &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                            this.hwColour );
    } else {
        __arm_2d_impl_rgb565_colour_filling_with_opacity(
                        ptTask->Param.tTileProcess.pBuffer,
                        ptTask->Param.tTileProcess.iStride,
                        &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                        this.hwColour,
                        this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb565_sw_tile_copy_with_des_mask()
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_copy_with_des_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb565_sw_tile_copy_with_masks()
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_copy_with_masks (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb565_sw_tile_copy_with_src_mask()
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_copy_with_src_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb565_sw_tile_fill_with_des_mask()
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_fill_with_des_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb565_sw_tile_fill_with_masks()
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_fill_with_masks (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb565_sw_tile_fill_with_src_mask()
arm_fsm_rt_t __arm_2d_rgb565_sw_tile_fill_with_src_mask (__arm_2d_sub_task_t * ptTask)
__arm_2d_rgb565_sw_transform()
arm_fsm_rt_t __arm_2d_rgb565_sw_transform (__arm_2d_sub_task_t * ptTask)
Definition at line 806 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
    __arm_2d_impl_rgb565_transform( &(ptTask->Param.tCopyOrig),
                                    &this.tTransform);
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb565_sw_transform_with_alpha()
arm_fsm_rt_t __arm_2d_rgb565_sw_transform_with_alpha (__arm_2d_sub_task_t * ptTask)
Definition at line 946 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_opa_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chOpacity) {
        __arm_2d_impl_rgb565_transform( &(ptTask->Param.tCopyOrig),
                                        &this.tTransform);
    } else {
        __arm_2d_impl_rgb565_transform_with_opacity(   &(ptTask->Param.tCopyOrig),
                                                &this.tTransform,
                                                this.chOpacity);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb565_sw_transform_with_src_mask()
arm_fsm_rt_t __arm_2d_rgb565_sw_transform_with_src_mask (__arm_2d_sub_task_t * ptTask)
Definition at line 1183 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_msk_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
#if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
    bool bIsMaskChannel8In32 = (ARM_2D_CHANNEL_8in32
            ==  ptTask->Param.tCopyOrigMask.tOrigMask.tColour.chScheme);
    if (bIsMaskChannel8In32) {
        __arm_2d_impl_rgb565_transform_with_src_chn_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
    } else
#endif
    {
        __arm_2d_impl_rgb565_transform_with_src_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb565_sw_transform_with_src_mask_and_opacity()
arm_fsm_rt_t __arm_2d_rgb565_sw_transform_with_src_mask_and_opacity (__arm_2d_sub_task_t * ptTask)
Definition at line 1409 of file arm_2d_transform.c.
{
    ARM_2D_IMPL(arm_2d_op_trans_msk_opa_t, ptTask->ptOP);
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
#if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
    bool bIsMaskChannel8In32 = (ARM_2D_CHANNEL_8in32
            ==  ptTask->Param.tCopyOrigMask.tOrigMask.tColour.chScheme);
#endif
    if (255 == this.chOpacity) {
    #if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        if (bIsMaskChannel8In32) {
            __arm_2d_impl_rgb565_transform_with_src_chn_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
        } else
    #endif
        {
            __arm_2d_impl_rgb565_transform_with_src_mask(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform);
        }
    } else {
    #if __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        if (bIsMaskChannel8In32) {
            __arm_2d_impl_rgb565_transform_with_src_chn_mask_and_opacity(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform,
                                                this.chOpacity);
        } else
    #endif
        {
            __arm_2d_impl_rgb565_transform_with_src_mask_and_opacity(
                                                &(ptTask->Param.tCopyOrigMask),
                                                &this.tTransform,
                                                this.chOpacity);
        }
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_sw_convert_colour_to_rgb565()
arm_fsm_rt_t __arm_2d_sw_convert_colour_to_rgb565 (__arm_2d_sub_task_t * ptTask)
Definition at line 147 of file arm_2d_conversion.c.
{
    ARM_2D_IMPL(arm_2d_op_cl_convt_t, ptTask->ptOP);
    if (!this.Source.ptTile->bHasEnforcedColour) {
        return (arm_fsm_rt_t)ARM_2D_ERR_MISSING_PARAM;
    }
    switch ( this.Source.ptTile->tInfo.tColourInfo.u3ColourSZ) {
        case ARM_2D_COLOUR_SZ_16BIT:
            /* no need to convert, return cpl directly */
            break;
        case ARM_2D_COLOUR_SZ_32BIT:
            __arm_2d_impl_cccn888_to_rgb565( ptTask->Param.tCopy.tSource.pBuffer,
                                            ptTask->Param.tCopy.tSource.iStride,
                                            ptTask->Param.tCopy.tTarget.pBuffer,
                                            ptTask->Param.tCopy.tTarget.iStride,
                                            &(ptTask->Param.tCopy.tCopySize));
            break;
        default:
            return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_cccn888_to_rgb565(), ARM_2D_COLOUR_SZ_16BIT, ARM_2D_COLOUR_SZ_32BIT, ARM_2D_ERR_MISSING_PARAM, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_sw_convert_colour_to_rgb888()
arm_fsm_rt_t __arm_2d_sw_convert_colour_to_rgb888 (__arm_2d_sub_task_t * ptTask)
Definition at line 175 of file arm_2d_conversion.c.
{
    ARM_2D_IMPL(arm_2d_op_cl_convt_t, ptTask->ptOP);
    if (!this.Source.ptTile->bHasEnforcedColour) {
        return (arm_fsm_rt_t)ARM_2D_ERR_MISSING_PARAM;
    }
    switch ( this.Source.ptTile->tInfo.tColourInfo.u3ColourSZ) {
        case ARM_2D_COLOUR_SZ_16BIT:
            __arm_2d_impl_rgb565_to_cccn888( ptTask->Param.tCopy.tSource.pBuffer,
                                            ptTask->Param.tCopy.tSource.iStride,
                                            ptTask->Param.tCopy.tTarget.pBuffer,
                                            ptTask->Param.tCopy.tTarget.iStride,
                                            &(ptTask->Param.tCopy.tCopySize));
            break;
        case ARM_2D_COLOUR_SZ_32BIT:
            /* no need to convert, return cpl directly */
            break;
        default:
            return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_rgb565_to_cccn888(), ARM_2D_COLOUR_SZ_16BIT, ARM_2D_COLOUR_SZ_32BIT, ARM_2D_ERR_MISSING_PARAM, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_sw_draw_point()
arm_fsm_rt_t __arm_2d_sw_draw_point (__arm_2d_sub_task_t * ptTask)
Definition at line 212 of file arm_2d_draw.c.
{
    ARM_2D_IMPL(arm_2d_op_drw_pt_t, ptTask->ptOP)
    switch (OP_CORE.ptOp->Info.Colour.u3ColourSZ) {
        case ARM_2D_COLOUR_SZ_8BIT:
            (*(uint8_t *)ptTask->Param.tTileProcess.pBuffer) = this.chColour;
            break;
        case ARM_2D_COLOUR_SZ_16BIT:
            (*(uint16_t *)ptTask->Param.tTileProcess.pBuffer) = this.hwColour;
            break;
        case ARM_2D_COLOUR_SZ_32BIT:
            (*(uint32_t *)ptTask->Param.tTileProcess.pBuffer) = this.wColour;
            break;
        default:
            return (arm_fsm_rt_t)ARM_2D_ERR_NOT_SUPPORT;
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_COLOUR_SZ_16BIT, ARM_2D_COLOUR_SZ_32BIT, ARM_2D_COLOUR_SZ_8BIT, ARM_2D_ERR_NOT_SUPPORT, ARM_2D_IMPL, arm_fsm_rt_cpl, chColour, hwColour, OP_CORE, and wColour.
__arm_mask_validate()
arm_2d_err_t __arm_mask_validate (const arm_2d_tile_t * ptSource, const arm_2d_tile_t * ptSrcMask, const arm_2d_tile_t * ptTarget, const arm_2d_tile_t * ptDesMask, uint32_t wMode)
Variable Documentation
__ARM_2D_IO_TABLE
const struct __arm_2d_io_table __ARM_2D_IO_TABLE extern
ARM_2D_CTRL
struct __arm_2d_op_control ARM_2D_CTRL extern