arm-2d: /Users/gabwan01/Documents/Work/CPMK/Git/EndpointAI/Kernels/Research/Arm-2D/Library/Source/arm_2d_alpha_blending.c File Reference
arm_2d_alpha_blending.c File Reference
#include "arm_2d.h"
#include "__arm_2d_impl.h"
#include "__arm_2d_alpha_blending.inc"
#include "__arm_2d_alpha_mask.inc"
#include "__arm_2d_alpha_blending_wrapper.inc"
Macros
#define __ARM_2D_IMPL__
#define __API_COLOUR gray8
#define __API_INT_TYPE uint8_t
#define __API_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_GRAY8
#define __API_COLOUR rgb565
#define __API_INT_TYPE uint16_t
#define __API_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_RGB565
#define __PATCH_ALPHA_BLENDING
#define __API_COLOUR cccn888
#define __API_INT_TYPE uint32_t
#define __API_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_CCCN888
#define __API_CAFWM_COLOUR gray8
#define __API_CAFWM_INT_TYPE uint8_t
#define __API_CAFWM_INT_TYPE_BIT_NUM 8
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_GRAY8
#define __API_CAFWM_CFG_1_HORIZONTAL_LINE 1
#define __API_CAFWM_COLOUR gray8
#define __API_CAFWM_INT_TYPE uint8_t
#define __API_CAFWM_INT_TYPE_BIT_NUM 8
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_GRAY8
#define __API_CAFWM_CFG_CHANNEL_8in32_SUPPORT 1
#define __API_CAFWM_COLOUR gray8
#define __API_CAFWM_INT_TYPE uint8_t
#define __API_CAFWM_INT_TYPE_BIT_NUM 8
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_GRAY8
#define __API_CAFWM_COLOUR rgb565
#define __API_CAFWM_INT_TYPE uint16_t
#define __API_CAFWM_INT_TYPE_BIT_NUM 16
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_RGB565
#define __API_CAFWM_CFG_1_HORIZONTAL_LINE 1
#define __API_CAFWM_COLOUR rgb565
#define __API_CAFWM_INT_TYPE uint16_t
#define __API_CAFWM_INT_TYPE_BIT_NUM 16
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_RGB565
#define __API_CAFWM_CFG_CHANNEL_8in32_SUPPORT 1
#define __API_CAFWM_COLOUR rgb565
#define __API_CAFWM_INT_TYPE uint16_t
#define __API_CAFWM_INT_TYPE_BIT_NUM 16
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_RGB565
#define __API_CAFWM_COLOUR cccn888
#define __API_CAFWM_INT_TYPE uint32_t
#define __API_CAFWM_INT_TYPE_BIT_NUM 32
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_CCCN888
#define __API_CAFWM_CFG_1_HORIZONTAL_LINE 1
#define __API_CAFWM_COLOUR cccn888
#define __API_CAFWM_INT_TYPE uint32_t
#define __API_CAFWM_INT_TYPE_BIT_NUM 32
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_CCCN888
#define __API_CAFWM_CFG_CHANNEL_8in32_SUPPORT 1
#define __API_CAFWM_COLOUR cccn888
#define __API_CAFWM_INT_TYPE uint32_t
#define __API_CAFWM_INT_TYPE_BIT_NUM 32
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_CCCN888
#define __API_ABW_COLOUR gray8
#define __API_ABW_INT_TYPE uint8_t
#define __API_ABW_INT_TYPE_BIT_NUM 8
#define __API_ABW_COLOUR_SZ ARM_2D_COLOUR_SZ_8BIT
#define __API_ABW_COLOUR rgb565
#define __API_ABW_INT_TYPE uint16_t
#define __API_ABW_INT_TYPE_BIT_NUM 16
#define __API_ABW_COLOUR_SZ ARM_2D_COLOUR_SZ_16BIT
#define __API_ABW_COLOUR cccn888
#define __API_ABW_INT_TYPE uint32_t
#define __API_ABW_INT_TYPE_BIT_NUM 32
#define __API_ABW_COLOUR_SZ ARM_2D_COLOUR_SZ_32BIT
Functions
void __arm_2d_impl_rgb565_alpha_blending_direct (const uint16_t *phwSource, const uint16_t *phwBackground, uint16_t *phwDestination, uint32_t wPixelCount, uint_fast16_t hwRatio)
void __arm_2d_impl_cccn888_alpha_blending_direct (const uint32_t *__RESTRICT pwSource, const uint32_t *__RESTRICT pwBackground, uint32_t *pwDestination, uint32_t wPixelCount, uint_fast16_t hwRatio)
arm_fsm_rt_t __arm_2d_gray8_sw_alpha_blending (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_alpha_blending (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_alpha_blending (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_mask (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_gray8_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_rgb565_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_cccn888_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t *ptTask)
__WEAK void __arm_2d_impl_rgb565_alpha_blending (uint16_t *__RESTRICT phwSourceBase, int16_t iSourceStride, uint16_t *__RESTRICT phwTargetBase, int16_t iTargetStride, arm_2d_size_t *__RESTRICT ptCopySize, uint_fast16_t hwRatio)
Variables
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_RGB565
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_CCCN888
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_AND_OPACITY_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_AND_OPACITY_RGB565
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_AND_OPACITY_CCCN888
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_RGB565
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_RGB888
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_WITH_COLOUR_KEYING_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_WITH_COLOUR_KEYING_RGB565
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_WITH_COLOUR_KEYING_RGB888
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_COLOUR_FILL_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_COLOUR_FILL_RGB565
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_COLOUR_FILL_RGB888
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_MASK_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_MASK_RGB565
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_MASK_CCCN888
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_SRC_MASK_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_SRC_MASK_RGB565
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_SRC_MASK_CCCN888
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_DES_MASK_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_DES_MASK_RGB565
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_DES_MASK_CCCN888
Macro Definition Documentation
__API_ABW_COLOUR [1/3]
#define __API_ABW_COLOUR gray8
Definition at line 196 of file arm_2d_alpha_blending.c.
__API_ABW_COLOUR [2/3]
#define __API_ABW_COLOUR rgb565
Definition at line 196 of file arm_2d_alpha_blending.c.
__API_ABW_COLOUR [3/3]
#define __API_ABW_COLOUR cccn888
Definition at line 196 of file arm_2d_alpha_blending.c.
__API_ABW_COLOUR_SZ [1/3]
#define __API_ABW_COLOUR_SZ ARM_2D_COLOUR_SZ_8BIT
Definition at line 199 of file arm_2d_alpha_blending.c.
__API_ABW_COLOUR_SZ [2/3]
#define __API_ABW_COLOUR_SZ ARM_2D_COLOUR_SZ_16BIT
Definition at line 199 of file arm_2d_alpha_blending.c.
__API_ABW_COLOUR_SZ [3/3]
#define __API_ABW_COLOUR_SZ ARM_2D_COLOUR_SZ_32BIT
Definition at line 199 of file arm_2d_alpha_blending.c.
__API_ABW_INT_TYPE [1/3]
#define __API_ABW_INT_TYPE uint8_t
Definition at line 197 of file arm_2d_alpha_blending.c.
__API_ABW_INT_TYPE [2/3]
#define __API_ABW_INT_TYPE uint16_t
Definition at line 197 of file arm_2d_alpha_blending.c.
__API_ABW_INT_TYPE [3/3]
#define __API_ABW_INT_TYPE uint32_t
Definition at line 197 of file arm_2d_alpha_blending.c.
__API_ABW_INT_TYPE_BIT_NUM [1/3]
#define __API_ABW_INT_TYPE_BIT_NUM 8
Definition at line 198 of file arm_2d_alpha_blending.c.
__API_ABW_INT_TYPE_BIT_NUM [2/3]
#define __API_ABW_INT_TYPE_BIT_NUM 16
Definition at line 198 of file arm_2d_alpha_blending.c.
__API_ABW_INT_TYPE_BIT_NUM [3/3]
#define __API_ABW_INT_TYPE_BIT_NUM 32
Definition at line 198 of file arm_2d_alpha_blending.c.
__API_CAFWM_CFG_1_HORIZONTAL_LINE [1/3]
#define __API_CAFWM_CFG_1_HORIZONTAL_LINE 1
Definition at line 163 of file arm_2d_alpha_blending.c.
__API_CAFWM_CFG_1_HORIZONTAL_LINE [2/3]
#define __API_CAFWM_CFG_1_HORIZONTAL_LINE 1
Definition at line 163 of file arm_2d_alpha_blending.c.
__API_CAFWM_CFG_1_HORIZONTAL_LINE [3/3]
#define __API_CAFWM_CFG_1_HORIZONTAL_LINE 1
Definition at line 163 of file arm_2d_alpha_blending.c.
__API_CAFWM_CFG_CHANNEL_8in32_SUPPORT [1/3]
#define __API_CAFWM_CFG_CHANNEL_8in32_SUPPORT 1
Definition at line 171 of file arm_2d_alpha_blending.c.
__API_CAFWM_CFG_CHANNEL_8in32_SUPPORT [2/3]
#define __API_CAFWM_CFG_CHANNEL_8in32_SUPPORT 1
Definition at line 171 of file arm_2d_alpha_blending.c.
__API_CAFWM_CFG_CHANNEL_8in32_SUPPORT [3/3]
#define __API_CAFWM_CFG_CHANNEL_8in32_SUPPORT 1
Definition at line 171 of file arm_2d_alpha_blending.c.
__API_CAFWM_COLOUR [1/9]
#define __API_CAFWM_COLOUR gray8
Definition at line 172 of file arm_2d_alpha_blending.c.
__API_CAFWM_COLOUR [2/9]
#define __API_CAFWM_COLOUR gray8
Definition at line 172 of file arm_2d_alpha_blending.c.
__API_CAFWM_COLOUR [3/9]
#define __API_CAFWM_COLOUR gray8
Definition at line 172 of file arm_2d_alpha_blending.c.
__API_CAFWM_COLOUR [4/9]
#define __API_CAFWM_COLOUR rgb565
Definition at line 172 of file arm_2d_alpha_blending.c.
__API_CAFWM_COLOUR [5/9]
#define __API_CAFWM_COLOUR rgb565
Definition at line 172 of file arm_2d_alpha_blending.c.
__API_CAFWM_COLOUR [6/9]
#define __API_CAFWM_COLOUR rgb565
Definition at line 172 of file arm_2d_alpha_blending.c.
__API_CAFWM_COLOUR [7/9]
#define __API_CAFWM_COLOUR cccn888
Definition at line 172 of file arm_2d_alpha_blending.c.
__API_CAFWM_COLOUR [8/9]
#define __API_CAFWM_COLOUR cccn888
Definition at line 172 of file arm_2d_alpha_blending.c.
__API_CAFWM_COLOUR [9/9]
#define __API_CAFWM_COLOUR cccn888
Definition at line 172 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE [1/9]
#define __API_CAFWM_INT_TYPE uint8_t
Definition at line 173 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE [2/9]
#define __API_CAFWM_INT_TYPE uint8_t
Definition at line 173 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE [3/9]
#define __API_CAFWM_INT_TYPE uint8_t
Definition at line 173 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE [4/9]
#define __API_CAFWM_INT_TYPE uint16_t
Definition at line 173 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE [5/9]
#define __API_CAFWM_INT_TYPE uint16_t
Definition at line 173 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE [6/9]
#define __API_CAFWM_INT_TYPE uint16_t
Definition at line 173 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE [7/9]
#define __API_CAFWM_INT_TYPE uint32_t
Definition at line 173 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE [8/9]
#define __API_CAFWM_INT_TYPE uint32_t
Definition at line 173 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE [9/9]
#define __API_CAFWM_INT_TYPE uint32_t
Definition at line 173 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE_BIT_NUM [1/9]
#define __API_CAFWM_INT_TYPE_BIT_NUM 8
Definition at line 174 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE_BIT_NUM [2/9]
#define __API_CAFWM_INT_TYPE_BIT_NUM 8
Definition at line 174 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE_BIT_NUM [3/9]
#define __API_CAFWM_INT_TYPE_BIT_NUM 8
Definition at line 174 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE_BIT_NUM [4/9]
#define __API_CAFWM_INT_TYPE_BIT_NUM 16
Definition at line 174 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE_BIT_NUM [5/9]
#define __API_CAFWM_INT_TYPE_BIT_NUM 16
Definition at line 174 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE_BIT_NUM [6/9]
#define __API_CAFWM_INT_TYPE_BIT_NUM 16
Definition at line 174 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE_BIT_NUM [7/9]
#define __API_CAFWM_INT_TYPE_BIT_NUM 32
Definition at line 174 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE_BIT_NUM [8/9]
#define __API_CAFWM_INT_TYPE_BIT_NUM 32
Definition at line 174 of file arm_2d_alpha_blending.c.
__API_CAFWM_INT_TYPE_BIT_NUM [9/9]
#define __API_CAFWM_INT_TYPE_BIT_NUM 32
Definition at line 174 of file arm_2d_alpha_blending.c.
__API_CAFWM_PIXEL_BLENDING [1/9]
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_GRAY8
Definition at line 175 of file arm_2d_alpha_blending.c.
__API_CAFWM_PIXEL_BLENDING [2/9]
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_GRAY8
Definition at line 175 of file arm_2d_alpha_blending.c.
__API_CAFWM_PIXEL_BLENDING [3/9]
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_GRAY8
Definition at line 175 of file arm_2d_alpha_blending.c.
__API_CAFWM_PIXEL_BLENDING [4/9]
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_RGB565
Definition at line 175 of file arm_2d_alpha_blending.c.
__API_CAFWM_PIXEL_BLENDING [5/9]
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_RGB565
Definition at line 175 of file arm_2d_alpha_blending.c.
__API_CAFWM_PIXEL_BLENDING [6/9]
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_RGB565
Definition at line 175 of file arm_2d_alpha_blending.c.
__API_CAFWM_PIXEL_BLENDING [7/9]
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_CCCN888
Definition at line 175 of file arm_2d_alpha_blending.c.
__API_CAFWM_PIXEL_BLENDING [8/9]
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_CCCN888
Definition at line 175 of file arm_2d_alpha_blending.c.
__API_CAFWM_PIXEL_BLENDING [9/9]
#define __API_CAFWM_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_CCCN888
Definition at line 175 of file arm_2d_alpha_blending.c.
__API_COLOUR [1/3]
#define __API_COLOUR gray8
adding support with c code template
Definition at line 100 of file arm_2d_alpha_blending.c.
__API_COLOUR [2/3]
#define __API_COLOUR rgb565
adding support with c code template
Definition at line 100 of file arm_2d_alpha_blending.c.
__API_COLOUR [3/3]
#define __API_COLOUR cccn888
adding support with c code template
Definition at line 100 of file arm_2d_alpha_blending.c.
__API_INT_TYPE [1/3]
#define __API_INT_TYPE uint8_t
Definition at line 101 of file arm_2d_alpha_blending.c.
__API_INT_TYPE [2/3]
#define __API_INT_TYPE uint16_t
Definition at line 101 of file arm_2d_alpha_blending.c.
__API_INT_TYPE [3/3]
#define __API_INT_TYPE uint32_t
Definition at line 101 of file arm_2d_alpha_blending.c.
__API_PIXEL_BLENDING [1/3]
#define __API_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_GRAY8
Definition at line 102 of file arm_2d_alpha_blending.c.
__API_PIXEL_BLENDING [2/3]
#define __API_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_RGB565
Definition at line 102 of file arm_2d_alpha_blending.c.
__API_PIXEL_BLENDING [3/3]
#define __API_PIXEL_BLENDING __ARM_2D_PIXEL_BLENDING_CCCN888
Definition at line 102 of file arm_2d_alpha_blending.c.
__ARM_2D_IMPL__
#define __ARM_2D_IMPL__
Definition at line 32 of file arm_2d_alpha_blending.c.
__PATCH_ALPHA_BLENDING
#define __PATCH_ALPHA_BLENDING
Definition at line 94 of file arm_2d_alpha_blending.c.
Function Documentation
__arm_2d_cccn888_sw_alpha_blending()
arm_fsm_rt_t __arm_2d_cccn888_sw_alpha_blending (__arm_2d_sub_task_t * ptTask)
Definition at line 752 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb32_copy(   ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize);
    } else {
        __arm_2d_impl_cccn888_alpha_blending(
                                            ptTask->Param.tCopy.tSource.pBuffer,
                                            ptTask->Param.tCopy.tSource.iStride,
                                            ptTask->Param.tCopy.tTarget.pBuffer,
                                            ptTask->Param.tCopy.tTarget.iStride,
                                            &(ptTask->Param.tCopy.tCopySize),
                                            this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_cccn888_sw_alpha_blending_with_colour_keying()
arm_fsm_rt_t __arm_2d_cccn888_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t * ptTask)
Definition at line 1603 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_cl_key_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb32_cl_key_copy(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.wColour);
    } else {
    __arm_2d_impl_cccn888_alpha_blending_colour_keying(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.chRatio,
                                    this.wColour);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_cccn888_sw_colour_filling_with_mask()
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_mask (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
Definition at line 1120 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_msk_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        __arm_2d_impl_cccn888_colour_filling_channel_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.hwColour);
    #endif
    } else {
        __arm_2d_impl_cccn888_colour_filling_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.hwColour);
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_cccn888_colour_filling_channel_mask(), __arm_2d_impl_cccn888_colour_filling_mask(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_cccn888_sw_colour_filling_with_mask_and_opacity()
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
< alpha tile
< alpha tile
Definition at line 1388 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_fill_cl_msk_opc_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        if (255 == this.chRatio) {
            __arm_2d_impl_cccn888_colour_filling_channel_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour);
        } else {
            __arm_2d_impl_cccn888_colour_filling_channel_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour,
                            this.chRatio);
        }
    #endif
    } else {
        if (255 == this.chRatio) {
            __arm_2d_impl_cccn888_colour_filling_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour);
        } else {
            __arm_2d_impl_cccn888_colour_filling_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour,
                            this.chRatio);
        }
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_cccn888_colour_filling_channel_mask(), __arm_2d_impl_cccn888_colour_filling_channel_mask_opacity(), __arm_2d_impl_cccn888_colour_filling_mask(), __arm_2d_impl_cccn888_colour_filling_mask_opacity(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_cccn888_sw_colour_filling_with_opacity()
arm_fsm_rt_t __arm_2d_cccn888_sw_colour_filling_with_opacity (__arm_2d_sub_task_t * ptTask)
Definition at line 911 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_opc_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_SZ_32BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb32_colour_filling(
                            ptTask->Param.tTileProcess.pBuffer,
                            ptTask->Param.tTileProcess.iStride,
                            &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                            this.wColour );
    } else {
        __arm_2d_impl_cccn888_colour_filling_with_opacity(
                        ptTask->Param.tTileProcess.pBuffer,
                        ptTask->Param.tTileProcess.iStride,
                        &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                        this.wColour,
                        this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_gray8_sw_alpha_blending()
arm_fsm_rt_t __arm_2d_gray8_sw_alpha_blending (__arm_2d_sub_task_t * ptTask)
Definition at line 703 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_c8bit_copy(   ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize);
    } else {
        __arm_2d_impl_gray8_alpha_blending(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &(ptTask->Param.tCopy.tCopySize),
                                    this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_gray8_sw_alpha_blending_with_colour_keying()
arm_fsm_rt_t __arm_2d_gray8_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t * ptTask)
Definition at line 1547 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_cl_key_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_GRAY8 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_c8bit_cl_key_copy(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.chColour);
    } else {
        __arm_2d_impl_gray8_alpha_blending_colour_keying(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.chRatio,
                                    this.chColour);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_gray8_sw_colour_filling_with_mask()
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_mask (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
Definition at line 1058 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_msk_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_16BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        __arm_2d_impl_gray8_colour_filling_channel_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.chColour);
    #endif
    } else {
        __arm_2d_impl_gray8_colour_filling_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.chColour);
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_gray8_colour_filling_channel_mask(), __arm_2d_impl_gray8_colour_filling_mask(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_gray8_sw_colour_filling_with_mask_and_opacity()
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
< alpha tile
< alpha tile
Definition at line 1283 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_fill_cl_msk_opc_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_16BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        if (255 == this.chRatio) {
            __arm_2d_impl_gray8_colour_filling_channel_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.chColour);
        } else {
            __arm_2d_impl_gray8_colour_filling_channel_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.chColour,
                            this.chRatio);
        }
    #endif
    } else {
        if (255 == this.chRatio) {
            __arm_2d_impl_gray8_colour_filling_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.chColour);
        } else {
            __arm_2d_impl_gray8_colour_filling_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.chColour,
                            this.chRatio);
        }
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_gray8_colour_filling_channel_mask(), __arm_2d_impl_gray8_colour_filling_channel_mask_opacity(), __arm_2d_impl_gray8_colour_filling_mask(), __arm_2d_impl_gray8_colour_filling_mask_opacity(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_gray8_sw_colour_filling_with_opacity()
arm_fsm_rt_t __arm_2d_gray8_sw_colour_filling_with_opacity (__arm_2d_sub_task_t * ptTask)
Definition at line 864 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_opc_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_GRAY8 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_c8bit_colour_filling(
                            ptTask->Param.tTileProcess.pBuffer,
                            ptTask->Param.tTileProcess.iStride,
                            &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                            this.chColour );
    } else {
        __arm_2d_impl_gray8_colour_filling_with_opacity(
                                ptTask->Param.tTileProcess.pBuffer,
                                ptTask->Param.tTileProcess.iStride,
                                &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                                this.chColour,
                                this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_impl_cccn888_alpha_blending_direct()
void __arm_2d_impl_cccn888_alpha_blending_direct (const uint32_t *__RESTRICT pwSource, const uint32_t *__RESTRICT pwBackground, uint32_t * pwDestination, uint32_t wPixelCount, uint_fast16_t hwRatio)
__arm_2d_impl_rgb565_alpha_blending()
__WEAK void __arm_2d_impl_rgb565_alpha_blending (uint16_t *__RESTRICT phwSourceBase, int16_t iSourceStride, uint16_t *__RESTRICT phwTargetBase, int16_t iTargetStride, arm_2d_size_t *__RESTRICT ptCopySize, uint_fast16_t hwRatio)
Definition at line 1637 of file arm_2d_alpha_blending.c.
{
    uint32_t iHeight = ptCopySize->iHeight;
    uint32_t iWidth  = ptCopySize->iWidth;
    uint16_t        ratioCompl = 256 - hwRatio;
    ARM_2D_UNUSED(ratioCompl);
    for (uint32_t y = 0; y < iHeight; y++) {
#if (defined (__ARM_ARCH_8_1M_MAIN__) && (__ARM_ARCH_8_1M_MAIN__ == 1))
        /* M55 NOMVE optimization */
        register unsigned loopCnt  __asm("lr");
        loopCnt = iWidth;
        __asm volatile(
            "   dls             lr, lr                                  \n"
            ".p2align 2                                                 \n"
            "1:                                                         \n"
            /* read source / target pixel  */
            "   ldrh            r4, [%[src]], #2                        \n"
            "   ldrh            r5, [%[pTarget]]                        \n"
            /* unpack R */
            "   and             r0, r4, #31                             \n"
            "   and             r1, r5, #31                             \n"
            /* unpack B */
            "   lsr             r2, r4, #11                             \n"
            "   lsr             r3, r5, #11                             \n"
            /* unpack G */
            "   ubfx            r4, r4, #5, #6                          \n"
            "   ubfx            r5, r5, #5, #6                          \n"
            /* mix */
            "   mul             r0, r0, %[ratio0]                       \n"
            "   mul             r4, r4, %[ratio0]                       \n"
            "   mul             r2, r2, %[ratio0]                       \n"
            "   mla             r0, %[ratio1], r1, r0                   \n"
            "   mla             r1, %[ratio1], r5, r4                   \n"
            /* pack R */
            "   ubfx            r0, r0, #8, #5                          \n"
            /* shift & mask G */
            "   and             r1, %[cst], r1, lsr #3                  \n"
            /* MLA moved here to fill stall */
            "   mla             r5, %[ratio1], r3, r2                   \n"
            /* pack G */
            "   add             r0, r0, r1                              \n"
            /* pack R */
            "   bic             r1, r5, #255                            \n"
            "   orr             r0, r0, r1, lsl #3                      \n"
            "   strh            r0, [%[pTarget]], #2                    \n"
            "   le              lr, 1b                                  \n"
            : [src] "+r" (phwSourceBase), [pTarget] "+r" (phwTargetBase),
              [cnt] "+r" (loopCnt)
            : [ratio1] "r" ((256 - (uint_fast16_t)hwRatio) ),
              [ratio0] "r" (hwRatio), [cst] "r" (0x7e0 /* mask G */)
            : "r0", "r1", "r2", "r3",
              "r4", "r5", "memory"
        );
#else
        for (uint32_t x = 0; x < iWidth; x++) {
            __arm_2d_color_fast_rgb_t srcPix, targetPix;
            __arm_2d_rgb565_unpack(*phwSourceBase++, &srcPix);
            __arm_2d_rgb565_unpack(*phwTargetBase, &targetPix);
            for (int i = 0; i < 3; i++) {
                uint16_t        tmp =
                    (uint16_t) (srcPix.RGBA[i] * hwRatio) +
                    (targetPix.RGBA[i] * ratioCompl);
                targetPix.RGBA[i] = (uint16_t) (tmp >> 8);
            }
            /* pack merged stream */
            *phwTargetBase++ = __arm_2d_rgb565_pack(&targetPix);
        }
#endif
        phwSourceBase += (iSourceStride - iWidth);
        phwTargetBase += (iTargetStride - iWidth);
    }
}
References __arm_2d_rgb565_pack(), __arm_2d_rgb565_unpack(), ARM_2D_UNUSED, and __arm_2d_color_fast_rgb_t::RGBA.
__arm_2d_impl_rgb565_alpha_blending_direct()
void __arm_2d_impl_rgb565_alpha_blending_direct (const uint16_t * phwSource, const uint16_t * phwBackground, uint16_t * phwDestination, uint32_t wPixelCount, uint_fast16_t hwRatio)
__arm_2d_rgb565_sw_alpha_blending()
arm_fsm_rt_t __arm_2d_rgb565_sw_alpha_blending (__arm_2d_sub_task_t * ptTask)
Definition at line 727 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb16_copy(   ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize);
    } else {
        __arm_2d_impl_rgb565_alpha_blending(
                                ptTask->Param.tCopy.tSource.pBuffer,
                                ptTask->Param.tCopy.tSource.iStride,
                                ptTask->Param.tCopy.tTarget.pBuffer,
                                ptTask->Param.tCopy.tTarget.iStride,
                                &(ptTask->Param.tCopy.tCopySize),
                                this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb565_sw_alpha_blending_with_colour_keying()
arm_fsm_rt_t __arm_2d_rgb565_sw_alpha_blending_with_colour_keying (__arm_2d_sub_task_t * ptTask)
Definition at line 1575 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_cl_key_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb16_cl_key_copy(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.hwColour);
    } else {
        __arm_2d_impl_rgb565_alpha_blending_colour_keying(
                                    ptTask->Param.tCopy.tSource.pBuffer,
                                    ptTask->Param.tCopy.tSource.iStride,
                                    ptTask->Param.tCopy.tTarget.pBuffer,
                                    ptTask->Param.tCopy.tTarget.iStride,
                                    &ptTask->Param.tCopy.tCopySize,
                                    this.chRatio,
                                    this.hwColour);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
__arm_2d_rgb565_sw_colour_filling_with_mask()
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_mask (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
Definition at line 1090 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_msk_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_16BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        __arm_2d_impl_rgb565_colour_filling_channel_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.hwColour);
    #endif
    } else {
        __arm_2d_impl_rgb565_colour_filling_mask(
                        ptTask->Param.tCopy.tTarget.pBuffer,
                        ptTask->Param.tCopy.tTarget.iStride,
                        ptTask->Param.tCopy.tSource.pBuffer,
                        ptTask->Param.tCopy.tSource.iStride,
                        &(ptTask->Param.tCopy.tCopySize),
                        this.hwColour);
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_rgb565_colour_filling_channel_mask(), __arm_2d_impl_rgb565_colour_filling_mask(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_rgb565_sw_colour_filling_with_mask_and_opacity()
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_mask_and_opacity (__arm_2d_sub_task_t * ptTask)
< alpha tile
< alpha tile
< alpha tile
< alpha tile
Definition at line 1336 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_alpha_fill_cl_msk_opc_t, ptTask->ptOP)
    //assert(ARM_2D_COLOUR_SZ_16BIT == OP_CORE.ptOp->Info.Colour.u3ColourSZ);
    if (ARM_2D_CHANNEL_8in32 == ptTask->Param.tCopy.tSource.tColour.chScheme) {
    #if !__ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
        return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    #else
        if (255 == this.chRatio) {
            __arm_2d_impl_rgb565_colour_filling_channel_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour);
        } else {
            __arm_2d_impl_rgb565_colour_filling_channel_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour,
                            this.chRatio);
        }
    #endif
    } else {
        if (255 == this.chRatio) {
            __arm_2d_impl_rgb565_colour_filling_mask(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour);
        } else {
            __arm_2d_impl_rgb565_colour_filling_mask_opacity(
                            ptTask->Param.tCopy.tTarget.pBuffer,
                            ptTask->Param.tCopy.tTarget.iStride,
                            ptTask->Param.tCopy.tSource.pBuffer,
                            ptTask->Param.tCopy.tSource.iStride,
                            &(ptTask->Param.tCopy.tCopySize),
                            this.hwColour,
                            this.chRatio);
        }
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_rgb565_colour_filling_channel_mask(), __arm_2d_impl_rgb565_colour_filling_channel_mask_opacity(), __arm_2d_impl_rgb565_colour_filling_mask(), __arm_2d_impl_rgb565_colour_filling_mask_opacity(), ARM_2D_CHANNEL_8in32, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_rgb565_sw_colour_filling_with_opacity()
arm_fsm_rt_t __arm_2d_rgb565_sw_colour_filling_with_opacity (__arm_2d_sub_task_t * ptTask)
Definition at line 887 of file arm_2d_alpha_blending.c.
{
    ARM_2D_IMPL(arm_2d_op_fill_cl_opc_t, ptTask->ptOP)
    assert(ARM_2D_COLOUR_RGB565 == OP_CORE.ptOp->Info.Colour.chScheme);
    if (255 == this.chRatio) {
        __arm_2d_impl_rgb16_colour_filling(
                            ptTask->Param.tTileProcess.pBuffer,
                            ptTask->Param.tTileProcess.iStride,
                            &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                            this.hwColour );
    } else {
        __arm_2d_impl_rgb565_colour_filling_with_opacity(
                        ptTask->Param.tTileProcess.pBuffer,
                        ptTask->Param.tTileProcess.iStride,
                        &(ptTask->Param.tTileProcess.tValidRegion.tSize),
                        this.hwColour,
                        this.chRatio);
    }
    return arm_fsm_rt_cpl;
}
References ARM_2D_IMPL.
Variable Documentation
ARM_2D_OP_ALPHA_BLENDING_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_GRAY8
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_GRAY8,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_ALPHA_BLENDING,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_ALPHA_BLENDING_GRAY8),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 1963 of file arm_2d_alpha_blending.c.
ARM_2D_OP_ALPHA_BLENDING_RGB565
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_RGB565
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_RGB565,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_ALPHA_BLENDING,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_ALPHA_BLENDING_RGB565),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 1981 of file arm_2d_alpha_blending.c.
ARM_2D_OP_ALPHA_BLENDING_RGB888
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_RGB888
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_CCCN888,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_ALPHA_BLENDING,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_ALPHA_BLENDING_RGB888),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 1999 of file arm_2d_alpha_blending.c.
ARM_2D_OP_ALPHA_BLENDING_WITH_COLOUR_KEYING_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_WITH_COLOUR_KEYING_GRAY8
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_GRAY8,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_ALPHA_BLENDING_WITH_COLOUR_KEYING,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_ALPHA_BLENDING_WITH_COLOUR_KEYING_GRAY8),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 2017 of file arm_2d_alpha_blending.c.
ARM_2D_OP_ALPHA_BLENDING_WITH_COLOUR_KEYING_RGB565
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_WITH_COLOUR_KEYING_RGB565
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_RGB565,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_ALPHA_BLENDING_WITH_COLOUR_KEYING,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_ALPHA_BLENDING_WITH_COLOUR_KEYING_RGB565),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 2035 of file arm_2d_alpha_blending.c.
ARM_2D_OP_ALPHA_BLENDING_WITH_COLOUR_KEYING_RGB888
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_BLENDING_WITH_COLOUR_KEYING_RGB888
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_CCCN888,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_ALPHA_BLENDING_WITH_COLOUR_KEYING,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_ALPHA_BLENDING_WITH_COLOUR_KEYING_RGB888),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 2053 of file arm_2d_alpha_blending.c.
ARM_2D_OP_ALPHA_COLOUR_FILL_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_COLOUR_FILL_GRAY8
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_GRAY8,
        },
        .Param = {
            .bHasSource     = false,
            .bHasTarget     = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_ALPHA_FILL_COLOUR,
        .LowLevelIO = {
            .ptTileProcessLike = ref_low_lv_io(__ARM_2D_IO_ALPHA_FILL_COLOUR_GRAY8),
        },
    },
}
Definition at line 2071 of file arm_2d_alpha_blending.c.
ARM_2D_OP_ALPHA_COLOUR_FILL_RGB565
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_COLOUR_FILL_RGB565
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_RGB565,
        },
        .Param = {
            .bHasSource     = false,
            .bHasTarget     = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_ALPHA_FILL_COLOUR,
        .LowLevelIO = {
            .ptTileProcessLike = ref_low_lv_io(__ARM_2D_IO_ALPHA_FILL_COLOUR_RGB565),
        },
    },
}
Definition at line 2088 of file arm_2d_alpha_blending.c.
ARM_2D_OP_ALPHA_COLOUR_FILL_RGB888
const __arm_2d_op_info_t ARM_2D_OP_ALPHA_COLOUR_FILL_RGB888
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_CCCN888,
        },
        .Param = {
            .bHasSource     = false,
            .bHasTarget     = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_ALPHA_FILL_COLOUR,
        .LowLevelIO = {
            .ptTileProcessLike = ref_low_lv_io(__ARM_2D_IO_ALPHA_FILL_COLOUR_RGB888),
        },
    },
}
Definition at line 2105 of file arm_2d_alpha_blending.c.
ARM_2D_OP_FILL_COLOUR_WITH_MASK_AND_OPACITY_CCCN888
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_AND_OPACITY_CCCN888
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_CCCN888,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bAllowEnforcedColour   = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK_AND_OPACITY,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_FILL_COLOUR_ALPHA_MASK_AND_OPACITY_CCCN888),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 1944 of file arm_2d_alpha_blending.c.
ARM_2D_OP_FILL_COLOUR_WITH_MASK_AND_OPACITY_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_AND_OPACITY_GRAY8
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_GRAY8,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bAllowEnforcedColour   = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK_AND_OPACITY,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_FILL_COLOUR_ALPHA_MASK_AND_OPACITY_GRAY8),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 1906 of file arm_2d_alpha_blending.c.
ARM_2D_OP_FILL_COLOUR_WITH_MASK_AND_OPACITY_RGB565
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_AND_OPACITY_RGB565
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_RGB565,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bAllowEnforcedColour   = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK_AND_OPACITY,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_FILL_COLOUR_ALPHA_MASK_AND_OPACITY_RGB565),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 1925 of file arm_2d_alpha_blending.c.
ARM_2D_OP_FILL_COLOUR_WITH_MASK_CCCN888
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_CCCN888
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_CCCN888,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bAllowEnforcedColour   = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_FILL_COLOUR_ALPHA_MASK_RGB888),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 1885 of file arm_2d_alpha_blending.c.
ARM_2D_OP_FILL_COLOUR_WITH_MASK_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_GRAY8
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_GRAY8,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bAllowEnforcedColour   = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_FILL_COLOUR_ALPHA_MASK_GRAY8),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 1847 of file arm_2d_alpha_blending.c.
ARM_2D_OP_FILL_COLOUR_WITH_MASK_RGB565
const __arm_2d_op_info_t ARM_2D_OP_FILL_COLOUR_WITH_MASK_RGB565
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_RGB565,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bAllowEnforcedColour   = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_FILL_COLOUR_WITH_MASK,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_FILL_COLOUR_ALPHA_MASK_RGB565),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 1866 of file arm_2d_alpha_blending.c.
ARM_2D_OP_TILE_COPY_WITH_DES_MASK_CCCN888
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_DES_MASK_CCCN888
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_CCCN888,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bHasSrcMask    = false,
            .bHasDesMask    = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COPY_WITH_TARGET_MASK,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COPY_WITH_DES_MASK_CCCN888),
            .ptFillLike = ref_low_lv_io(__ARM_2D_IO_FILL_WITH_DES_MASK_CCCN888),
        },
    },
}
Definition at line 2288 of file arm_2d_alpha_blending.c.
ARM_2D_OP_TILE_COPY_WITH_DES_MASK_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_DES_MASK_GRAY8
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_GRAY8,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bHasSrcMask    = false,
            .bHasDesMask    = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COPY_WITH_TARGET_MASK,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COPY_WITH_DES_MASK_GRAY8),
            .ptFillLike = ref_low_lv_io(__ARM_2D_IO_FILL_WITH_DES_MASK_GRAY8),
        },
    },
}
Definition at line 2246 of file arm_2d_alpha_blending.c.
ARM_2D_OP_TILE_COPY_WITH_DES_MASK_RGB565
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_DES_MASK_RGB565
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_RGB565,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bHasSrcMask    = false,
            .bHasDesMask    = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COPY_WITH_TARGET_MASK,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COPY_WITH_DES_MASK_RGB565),
            .ptFillLike = ref_low_lv_io(__ARM_2D_IO_FILL_WITH_DES_MASK_RGB565),
        },
    },
}
Definition at line 2267 of file arm_2d_alpha_blending.c.
ARM_2D_OP_TILE_COPY_WITH_MASK_CCCN888
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_MASK_CCCN888
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_CCCN888,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bHasSrcMask    = true,
            .bHasDesMask    = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COPY_WITH_MASKS,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COPY_WITH_MASKS_CCCN888),
            .ptFillLike = ref_low_lv_io(__ARM_2D_IO_FILL_WITH_MASKS_CCCN888),
        },
    },
}
Definition at line 2164 of file arm_2d_alpha_blending.c.
ARM_2D_OP_TILE_COPY_WITH_MASK_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_MASK_GRAY8
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_GRAY8,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bHasSrcMask    = true,
            .bHasDesMask    = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COPY_WITH_MASKS,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COPY_WITH_MASKS_GRAY8),
            .ptFillLike = ref_low_lv_io(__ARM_2D_IO_FILL_WITH_MASKS_GRAY8),
        },
    },
}
Definition at line 2122 of file arm_2d_alpha_blending.c.
ARM_2D_OP_TILE_COPY_WITH_MASK_RGB565
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_MASK_RGB565
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_RGB565,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bHasSrcMask    = true,
            .bHasDesMask    = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COPY_WITH_MASKS,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COPY_WITH_MASKS_RGB565),
            .ptFillLike = ref_low_lv_io(__ARM_2D_IO_FILL_WITH_MASKS_RGB565),
        },
    },
}
Definition at line 2143 of file arm_2d_alpha_blending.c.
ARM_2D_OP_TILE_COPY_WITH_SRC_MASK_CCCN888
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_SRC_MASK_CCCN888
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_CCCN888,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bHasSrcMask    = true,
            .bHasDesMask    = false,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COPY_WITH_SOURCE_MASK,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COPY_WITH_SRC_MASK_CCCN888),
            .ptFillLike = ref_low_lv_io(__ARM_2D_IO_FILL_WITH_SRC_MASK_CCCN888),
        },
    },
}
Definition at line 2226 of file arm_2d_alpha_blending.c.
ARM_2D_OP_TILE_COPY_WITH_SRC_MASK_GRAY8
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_SRC_MASK_GRAY8
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_GRAY8,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bHasSrcMask    = true,
            .bHasDesMask    = false,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COPY_WITH_SOURCE_MASK,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COPY_WITH_SRC_MASK_GRAY8),
            .ptFillLike = ref_low_lv_io(__ARM_2D_IO_FILL_WITH_SRC_MASK_GRAY8),
        },
    },
}
Definition at line 2184 of file arm_2d_alpha_blending.c.
ARM_2D_OP_TILE_COPY_WITH_SRC_MASK_RGB565
const __arm_2d_op_info_t ARM_2D_OP_TILE_COPY_WITH_SRC_MASK_RGB565
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_RGB565,
        },
        .Param = {
            .bHasSource     = true,
            .bHasTarget     = true,
            .bHasSrcMask    = true,
            .bHasDesMask    = false,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COPY_WITH_SOURCE_MASK,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COPY_WITH_SRC_MASK_RGB565),
            .ptFillLike = ref_low_lv_io(__ARM_2D_IO_FILL_WITH_SRC_MASK_RGB565),
        },
    },
}
Definition at line 2205 of file arm_2d_alpha_blending.c.