arm-2d: /Users/gabwan01/Documents/Work/CPMK/Git/EndpointAI/Kernels/Research/Arm-2D/Library/Source/arm_2d_conversion.c File Reference
arm_2d_conversion.c File Reference
#include "arm_2d.h"
#include "__arm_2d_impl.h"
Macros
#define __ARM_2D_IMPL__
Functions
void __arm_2d_impl_cccn888_to_rgb565 (uint32_t *__RESTRICT pwSource, int16_t iSourceStride, uint16_t *__RESTRICT phwTarget, int16_t iTargetStride, arm_2d_size_t *__RESTRICT ptCopySize)
void __arm_2d_impl_rgb565_to_cccn888 (uint16_t *__RESTRICT phwSourceBase, int16_t iSourceStride, uint32_t *__RESTRICT pwTargetBase, int16_t iTargetStride, arm_2d_size_t *__RESTRICT ptCopySize)
arm_fsm_rt_t __arm_2d_sw_convert_colour_to_rgb565 (__arm_2d_sub_task_t *ptTask)
arm_fsm_rt_t __arm_2d_sw_convert_colour_to_rgb888 (__arm_2d_sub_task_t *ptTask)
Variables
const __arm_2d_op_info_t ARM_2D_OP_CONVERT_TO_RGB565
const __arm_2d_op_info_t ARM_2D_OP_CONVERT_TO_RGB888
Macro Definition Documentation
__ARM_2D_IMPL__
#define __ARM_2D_IMPL__
Definition at line 33 of file arm_2d_conversion.c.
Function Documentation
__arm_2d_impl_cccn888_to_rgb565()
__WEAK void __arm_2d_impl_cccn888_to_rgb565 (uint32_t *__RESTRICT pwSource, int16_t iSourceStride, uint16_t *__RESTRICT phwTarget, int16_t iTargetStride, arm_2d_size_t *__RESTRICT ptCopySize)
Definition at line 208 of file arm_2d_conversion.c.
{
    for (int_fast16_t y = 0; y < ptCopySize->iHeight; y++) {
        const uint32_t *__RESTRICT pwSource = pwSourceBase;
        uint16_t *__RESTRICT phwTarget = phwTargetBase;
        for (int_fast16_t x = 0; x < ptCopySize->iWidth; x++) {
            arm_2d_color_rgba8888_t wSrcPixel;
            __arm_2d_color_fast_rgb_t      hwTargetPixel;
            wSrcPixel.tValue = *pwSource++;
            hwTargetPixel.R = wSrcPixel.u8R;
            hwTargetPixel.G = wSrcPixel.u8G;
            hwTargetPixel.B = wSrcPixel.u8B;
            *phwTarget++ = __arm_2d_rgb565_pack(&hwTargetPixel);
        }
        pwSourceBase += iSourceStride;
        phwTargetBase += iTargetStride;
    }
}
References __arm_2d_rgb565_pack(), __RESTRICT, __arm_2d_color_fast_rgb_t::B, __arm_2d_color_fast_rgb_t::G, __arm_2d_color_fast_rgb_t::R, arm_2d_color_rgba8888_t::tValue, arm_2d_color_rgba8888_t::u8B, arm_2d_color_rgba8888_t::u8G, and arm_2d_color_rgba8888_t::u8R.
Referenced by __arm_2d_sw_convert_colour_to_rgb565().
__arm_2d_impl_rgb565_to_cccn888()
__WEAK void __arm_2d_impl_rgb565_to_cccn888 (uint16_t *__RESTRICT phwSourceBase, int16_t iSourceStride, uint32_t *__RESTRICT pwTargetBase, int16_t iTargetStride, arm_2d_size_t *__RESTRICT ptCopySize)
Definition at line 237 of file arm_2d_conversion.c.
{
    for (int_fast16_t y = 0; y < ptCopySize->iHeight; y++) {
        const uint16_t *__RESTRICT phwSource = phwSourceBase;
        uint32_t       *__RESTRICT pwTarget = pwTargetBase;
        for (int_fast16_t x = 0; x < ptCopySize->iWidth; x++) {
            __arm_2d_color_fast_rgb_t      hwSrcPixel;
            arm_2d_color_rgba8888_t wTargetPixel;
            __arm_2d_rgb565_unpack(*phwSource++, &hwSrcPixel);
            wTargetPixel.u8R = hwSrcPixel.R;
            wTargetPixel.u8G = hwSrcPixel.G;
            wTargetPixel.u8B = hwSrcPixel.B;
            wTargetPixel.u8A = 0xFF;
            *pwTarget++ = wTargetPixel.tValue;
        }
        phwSourceBase += iSourceStride;
        pwTargetBase += iTargetStride;
    }
}
References __arm_2d_rgb565_unpack(), __RESTRICT, __arm_2d_color_fast_rgb_t::B, __arm_2d_color_fast_rgb_t::G, __arm_2d_color_fast_rgb_t::R, arm_2d_color_rgba8888_t::tValue, arm_2d_color_rgba8888_t::u8A, arm_2d_color_rgba8888_t::u8B, arm_2d_color_rgba8888_t::u8G, and arm_2d_color_rgba8888_t::u8R.
Referenced by __arm_2d_sw_convert_colour_to_rgb888().
__arm_2d_sw_convert_colour_to_rgb565()
arm_fsm_rt_t __arm_2d_sw_convert_colour_to_rgb565 (__arm_2d_sub_task_t * ptTask)
Definition at line 147 of file arm_2d_conversion.c.
{
    ARM_2D_IMPL(arm_2d_op_cl_convt_t, ptTask->ptOP);
    if (!this.Source.ptTile->bHasEnforcedColour) {
        return (arm_fsm_rt_t)ARM_2D_ERR_MISSING_PARAM;
    }
    switch ( this.Source.ptTile->tInfo.tColourInfo.u3ColourSZ) {
        case ARM_2D_COLOUR_SZ_16BIT:
            /* no need to convert, return cpl directly */
            break;
        case ARM_2D_COLOUR_SZ_32BIT:
            __arm_2d_impl_cccn888_to_rgb565( ptTask->Param.tCopy.tSource.pBuffer,
                                            ptTask->Param.tCopy.tSource.iStride,
                                            ptTask->Param.tCopy.tTarget.pBuffer,
                                            ptTask->Param.tCopy.tTarget.iStride,
                                            &(ptTask->Param.tCopy.tCopySize));
            break;
        default:
            return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_cccn888_to_rgb565(), ARM_2D_COLOUR_SZ_16BIT, ARM_2D_COLOUR_SZ_32BIT, ARM_2D_ERR_MISSING_PARAM, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
__arm_2d_sw_convert_colour_to_rgb888()
arm_fsm_rt_t __arm_2d_sw_convert_colour_to_rgb888 (__arm_2d_sub_task_t * ptTask)
Definition at line 175 of file arm_2d_conversion.c.
{
    ARM_2D_IMPL(arm_2d_op_cl_convt_t, ptTask->ptOP);
    if (!this.Source.ptTile->bHasEnforcedColour) {
        return (arm_fsm_rt_t)ARM_2D_ERR_MISSING_PARAM;
    }
    switch ( this.Source.ptTile->tInfo.tColourInfo.u3ColourSZ) {
        case ARM_2D_COLOUR_SZ_16BIT:
            __arm_2d_impl_rgb565_to_cccn888( ptTask->Param.tCopy.tSource.pBuffer,
                                            ptTask->Param.tCopy.tSource.iStride,
                                            ptTask->Param.tCopy.tTarget.pBuffer,
                                            ptTask->Param.tCopy.tTarget.iStride,
                                            &(ptTask->Param.tCopy.tCopySize));
            break;
        case ARM_2D_COLOUR_SZ_32BIT:
            /* no need to convert, return cpl directly */
            break;
        default:
            return (arm_fsm_rt_t)ARM_2D_ERR_UNSUPPORTED_COLOUR;
    }
    return arm_fsm_rt_cpl;
}
References __arm_2d_impl_rgb565_to_cccn888(), ARM_2D_COLOUR_SZ_16BIT, ARM_2D_COLOUR_SZ_32BIT, ARM_2D_ERR_MISSING_PARAM, ARM_2D_ERR_UNSUPPORTED_COLOUR, ARM_2D_IMPL, and arm_fsm_rt_cpl.
Variable Documentation
ARM_2D_OP_CONVERT_TO_RGB565
const __arm_2d_op_info_t ARM_2D_OP_CONVERT_TO_RGB565
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_RGB565,
        },
        .Param = {
            .bHasSource             = true,
            .bHasTarget             = true,
            .bAllowEnforcedColour   = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COLOUR_FORMAT_CONVERSION,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COLOUR_CONVERT_TO_RGB565),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 278 of file arm_2d_conversion.c.
ARM_2D_OP_CONVERT_TO_RGB888
const __arm_2d_op_info_t ARM_2D_OP_CONVERT_TO_RGB888
Initial value:
= {
    .Info = {
        .Colour = {
            .chScheme   = ARM_2D_COLOUR_CCCN888,
        },
        .Param = {
            .bHasSource             = true,
            .bHasTarget             = true,
            .bAllowEnforcedColour   = true,
        },
        .chOpIndex      = __ARM_2D_OP_IDX_COLOUR_FORMAT_CONVERSION,
        .LowLevelIO = {
            .ptCopyLike = ref_low_lv_io(__ARM_2D_IO_COLOUR_CONVERT_TO_RGB888),
            .ptFillLike = NULL,
        },
    },
}
Definition at line 298 of file arm_2d_conversion.c.